### ISSUE TITLE
cannot use config.CPUReservation (type int64) as type *int64 in assignment

### ISSUE THREAD

**Issue by michaelhajjar** [jetbrains-infra/packer-builder-vsphere#103]
getting the following error when trying to build the packer drivers from source (with build.sh):

/usr/local/go/src/packer-builder-vsphere/vendor/github.com/jetbrains-infra/packer-builder-vsphere/driver/vm.go:380:22: cannot use config.CPUReservation (type int64) as type *int64 in assignment
/usr/local/go/src/packer-builder-vsphere/vendor/github.com/jetbrains-infra/packer-builder-vsphere/driver/vm.go:381:16: cannot use config.CPULimit (type int64) as type *int64 in assignment
/usr/local/go/src/packer-builder-vsphere/vendor/github.com/jetbrains-infra/packer-builder-vsphere/driver/vm.go:385:22: cannot use config.RAMReservation (type int64) as type *int64 in assignment

this is with the master branch. What am I doing wrong?

Go version: go version go1.10.2 linux/amd64

**Comment by mkuzmin** [comment]
run `dep ensure`, I switched dependency to govmomi 0.17 in 903febc4ea8ab540e7bd4a3d235e32346076c2ca

**Comment by michaelhajjar** [comment]
thnx mkuzmin!
