### ISSUE TITLE
Separate Build on removed hardcoded file path 

### ISSUE THREAD

**Issue by hongjoonchew** [jetbrains-infra/packer-builder-vsphere#106]
Currently I'm working on a vSphere that is managed separately, and the folder path is currently 
`/Host/` when the finder looks for '/Host/vm/'. Is there a way to go about this with the current build?

#86 I noticed this PR was not made due to business decisions. But could there be a separate build to accommodate this?

**Comment by hongjoonchew** [comment]
I am currently running with these values:
`"builders": [
    {
      "boot_wait": "20m",
      "communicator": "none",
      "disk_size": 100000,
      "floppy_files": [
        "appliance.cfg"
      ],
      "guest_os_type": "centos6-64",
      "iso_paths": ["isopath goes here"],
      "shutdown_command": "<enter>",
      "type": "vsphere-iso",
      "vcenter_server": "SERVER",
      "username": "{{user `user_name`}}",
      "password": "{{user `pass`}}",
      "insecure_connection": "true",
      "host": "HOST",
      "datacenter": "DATACENTER"
      "datastore": "DATASTORE",
      "vm_name": "test",
      "ram": "8096",
      "CPUs" : 2,
      "convert_to_template": true,
      "network_card": "vmxnet3",
      "network": "VM Network",
      "resource_pool": "/host"
    }
  ]` 
And the output is 
`
==> vsphere-iso: Creating VM...
Build 'vsphere-iso' errored: error creating vm: folder '/DATACENTER/vm/' not found
`

The directory that is setup is actually `/DATACENTER/` instead of `/DATACENTER/vm/`, so it would always return the folder not found.

**Comment by hongjoonchew** [comment]
I accidentally closed it by accident. But this is not solved yet.

**Comment by mkuzmin** [comment]
So far I don't think these issues are related.
Try to add `folder` parameter, and create VM in some subfolder. Does it work?
Do you have permissions to create VMs in the root folder manually?

**Comment by hongjoonchew** [comment]
I added `folder: "test"` and the output I got was 
```
==> vsphere-iso: Creating VM...
Build 'vsphere-iso' errored: error creating vm: folder '/DATACENTER/vm/test/' not found
```

I do have permissions to create VMs in the root folder manually, but I would like to read `DATACENTER/` instead.

**Comment by mkuzmin** [comment]
We have documented required permissions in [README](https://github.com/jetbrains-infra/packer-builder-vsphere/blob/master/README.md#required-vsphere-permissions).

**Comment by nargmarg** [comment]
Could you explain why did you close this issue? The required permission doesn't fixed the issue. Thanks.

**Comment by RVB0904** [comment]
I faced unresolvable folder errors when using convert_to_template. After removing this option, the strange folder errors were gone.
