### ISSUE TITLE
Not an issue - just a compliment

### ISSUE THREAD

**Issue by jcoconnor** [jetbrains-infra/packer-builder-vsphere#109]
Just want to note that after working thru a number of issues, I've successfully used the plug-in to build windows-10 on our vSphere host.

The new floppy additions are excellent and makes it a very flexible tool.

One minor observation - may put up a PR for it eventually.
In the Windows-10 case, you are adding pvsci floppy to load the drivers into WinPE.
This isn't actually necessary, as you can also specify the path on the windows.iso drive, i.e. 
```<Path>E:\Program Files\VMware\VMware Tools\Drivers\pvscsi\Win8</Path>``` and pick it up from there rather than loading an additional floppy drive.

Thanks again

**Comment by mkuzmin** [comment]
I agree, but my goal was using original ISO images provided by vendors - Microsoft and VMware.
All customizations are explicitly placed in standalone artifacts.
