### ISSUE TITLE
ISO builder does not support building VMs at hardware version 9

### ISSUE THREAD

**Issue by cfryanr** [jetbrains-infra/packer-builder-vsphere#110]
Thanks for creating this open source tool.  It's fantastic!

We're using the ISO builder to create VMs on vSphere 6.5, and we would like those VMs to be usable on older versions of vSphere, so we are setting the VM hardware version to version 9.  The builder is able to create the VM with the appropriate hardware version.  However, that VM cannot actually boot on older versions of vSphere.

The issue is that the code creates a CDROM drive and attaches it to a SATA controller.  SATA controllers are not supported by hardware version 9 ([citation](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-789C3913-1053-4850-A0F0-E29C3D32B6DA.html)).  Any VM that has a SATA controller will not boot on older vSpheres.  Luckily, IDE controllers are supported by every hardware version, so the solution is simply to always use an IDE controller to attach the CDROM drive.

We implemented this SATA->IDE change in our fork to make sure that this approach would work ([see commit diff](https://github.com/pivotal-cf/packer-builder-vsphere/commit/6ae19a2a5444efd33247c8b90f12610847deb09d)).  It worked great!  Note that this commit was based on your v2.0-beta4 code, so in addition to changing the CDROM's controller, we also had to add the ability to set the hardware version.  It appears that you have since added he ability to set the hardware version to v2.0, so you can ignore those portions of the commit.

Might you consider making a similar change to remove the SATA controller and replace it with an IDE controller as an enhancement request?

Thanks for a great tool!

**Comment by mkuzmin** [comment]
I agree, we need to make SATA optional, and use IDE by default.
The only reason using it was macOS - not a mainstream use case

**Comment by mkuzmin** [comment]
@cfryanr I need your help here.
If I set hardware version to 9, even for a minimal VM configuration, vSphere API returns an error:
```
The virtual machine version is not compatible with the version of the host 'esxi-1.vsphere65.test'.
```

Here is a snippet of code 
https://gist.github.com/mkuzmin/afea4017b38c47a9b09a76bd2a6242e0

Any ideas what would be a reason?

**Comment by cfryanr** [comment]
Hi,

This works in our fork, which we are still using. However, our fork is
based on an old version of the project. I suspect that perhaps a later
version of the project might have introduced a different hardware
incompatibility aside from the SATA controller. Take a look at this page to
see what is allowed/disallowed in hardware version 9:

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-789C3913-1053-4850-A0F0-E29C3D32B6DA.html

I’ve asked my teammates if they have some time to please see if they could
help you more.

**Comment by mkuzmin** [comment]
My minimal gist above contains nothing special, and still reproduces the issue.
I appreciate if you directly communicate this to [govmomi](https://github.com/vmware/govmomi) team or VMware support.
