### ISSUE TITLE
new plugin (v2.0) stuck at anaconda (centos7/rhel7), vsphere 6

### ISSUE THREAD

**Issue by michaelhajjar** [jetbrains-infra/packer-builder-vsphere#112]
Thanks for the great work you guys have done!
I really appreciate it.

I have a problem using the new plugin (the pre-release, v2.0beta4 works fine). 
When trying to create a template with centos7/rhel7 using the new plugin, the VM is getting a black screen after the anaconda screen. When using the older version, it works just fine. Also tried downloading the latest version of packer, but no succes :(. 

Anyone else having this problem?

here is my packer file:
```
{
  "builders": [
    {
      "type": "vsphere-iso",

      "vcenter_server":      "{{ user `vcenter_host` }}",
      "username":            "{{ user `vcenter_user` }}",
      "password":            "{{ user `vcenter_password` }}",
      "insecure_connection": "true",
      "ssh_username": "{{ user `ssh_user` }}",
      "ssh_password": "{{ user `ssh_password` }}",

      "datacenter": "{{ user `dc` }}",
      "cluster": "{{ user `cluster` }}",
      "network": "{{ user `network` }}",
      "network_card": "vmxnet3",
      "datastore": "{{ user `storage` }}",
      "vm_name": "{{ user `vm_name` }}",
      "guest_os_type": "rhel7_64Guest",

      "CPUs":             "{{ user `cpu_cores` }}",
      "RAM":              "{{ user `ram_mb` }}",
      "RAM_reserve_all": true,

      "disk_controller_type":  "pvscsi",
      "disk_size":        "{{ user `disk_size_gb` }}",
      "disk_thin_provisioned": true,
      "folder": "{{ user `template_dir` }}",

      "iso_paths": [
        "{{ user `iso_path` }}"
      ],
      "floppy_files": [
        "{{ user `ks_file` }}"
      ],
      "boot_order": "disk,cdrom",
      "convert_to_template": true
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "inline": ["rm -rf /etc/yum.repos.d/*"],
      "execute_command": "echo 'root' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
      "pause_before": "10s"
    },

    { 
      "type": "file",
      "source": "repos/",
      "destination": "/etc/yum.repos.d"
    },

    {
      "type": "shell",
      "execute_command": "echo 'root' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
      "script": "scripts/centos7.sh",
      "expect_disconnect": "true"
    }
  ]
}

```

the vmware engineer is saying that it is trying to do 2 steps at the same time ?

after this screen, it gets a black screen and wont respond anymore.

![naamloos](https://user-images.githubusercontent.com/37404682/40616489-996eaaa2-628b-11e8-836e-a2ad27044cc8.png)

using against the Vsphere api version 6.

**Comment by sudomateo** [comment]
I'm on 6.5 and I my build hangs as well when using the 2.0 release. The 2.0 beta4 works using the same packer json file. Worst part is, the VM gets stuck in a weird state that forces me to log into the ESXi host and manually remove the VM using esxcli.

**Comment by haije** [comment]
I have exactly the same problem om vSphere 6.0. The VM hangs and is forced in a weird state as well. It takes about 15-30 minutes before de vm is removed. Also, the vmx files looks about the same.

**Comment by rolfberkenbosch** [comment]
I have exactly the same  problem.

**Comment by pgiuliano** [comment]
I get the feeling 104 is the same here.

**Comment by pgiuliano** [comment]
If you attempt to restart the "hung" VM the request seems to take much longer than epected but after the restart the build then continues without hanging

**Comment by embusalacchi** [comment]
Happening with Windows installs as well - also noticing the VM is totally unresponsive in my GUI when trying to work with it.  See my comment here - https://github.com/jetbrains-infra/packer-builder-vsphere/issues/119

**Comment by mkuzmin** [comment]
I'm sorry this took so much time. Version 2.0.1 fixes that.
