### ISSUE TITLE
Support Windows guests

### ISSUE THREAD

**Issue by mkuzmin** [jetbrains-infra/packer-builder-vsphere#12]
Connect to VM by WinRM

**Comment by SurferL** [comment]
Is this still under development per chance?

**Comment by idoru78** [comment]
You could install OpenSSH on the base machine?

**Comment by SurferL** [comment]
@idoru78 I gave that a try, but couldn't connect with it. Did you manage to get it working?

**Comment by idoru78** [comment]
Only just found this today so not yet. The plugin solves a lot of problems for me but this is a bit of a spanner in the works.

**Comment by SurferL** [comment]
Okay, if you do manage to get it working with a windows host please let me know how! 

I can't use this in the current state as most of the VMs I'm working with are Windows hosts, and using packer/ansible on top of it as well.

**Comment by mkuzmin** [comment]
Sorry for the delay, I'll come back to this feature soon.

**Comment by mkuzmin** [comment]
I've tested the plugin with a minimal config, and it works file with no modifications.
```
{
  "builders": [
    {
      "type": "vsphere",
      ...
      "communicator": "winrm",
      "winrm_username": "Administrator",
      "winrm_password": "secret"
    }
  ],
  "provisioners": [
    {
      "type": "windows-shell",
      "inline": [ "echo 123" ]
    }
  ]
}
```
Do you experience any particular issues?

**Comment by SurferL** [comment]
I've managed to get it working with the minimal example you provided above as well.

**Comment by mkuzmin** [comment]
OK, let's consider this feature done. 
Please open separate issues if you meet any particular problems.
