### ISSUE TITLE
Need to create Packer image with CDRom drive

### ISSUE THREAD

**Issue by stacycarter** [jetbrains-infra/packer-builder-vsphere#133]
Would like the resulting vSphere template that I'm building with Packer to include a CDROM drive (IDE).  It seems like this Packer plugin doesn't support a "cdrom_adapter_type" line in the json?  Would be helpful if this Packer plugin supported it.

**Comment by samsanthana** [comment]
We also have same issue.  Looking at the code it seems if the config has valid isopath it should create cd-rom with the ISO, but the resulted template doesn't have cd-rom.

**Comment by Geogboe** [comment]
From the vCenter console, it doesn't look like you can modify template hardware settings. ( like adding a cdrom ) my I don't think packer can make this change to the template. What we're noticing though is that, when packer shuts down the VM ( before converting it to a template) it strips off the cdrom and controller. 

We commented out the code in the go file to which strips off the cdrom at shutdown and now it works. Any VMs created from that template now have a cdrom attached. 

Is there any reason packer *has* to strip off the cdrom at shutdown? Can it not just eject the media?

**Comment by michaelhajjar** [comment]
Lol, we have exactly the same problem.... using user-data iso (cloud-init) for initalizing our virtual machines on Vsphere platform.

**Comment by chitashvili** [comment]
Hello, I had same issue I needed cd rom to be attached to VM before I start importing it to OVF and I did following:
After VM is create by packer I have stage in Jenkins pipeline to attach CD room by govc tool:
>   govc device.cdrom.add -vm $vm
But in this case you can not use conver_to_tamplate feature from packer, but you can do it by other tools like govc for example: 
> Usage: govc vm.markastemplate [OPTIONS] VM...

**Comment by mkuzmin** [comment]
IDE/SATA device type fill be fixed in #110
