### ISSUE TITLE
Floppy images not deleted on teardown, VM folders remain

### ISSUE THREAD

**Issue by corrigat** [jetbrains-infra/packer-builder-vsphere#137]
Thank you for this plugin, and apologies for being unable to submit a PR.

When a build is interrupted with ^C, the VM is torn down and all files related to the VM are deleted. The floppy image however is not removed, which is causing directories on the datastores to pile up. Right now I've got [BUILDVOL01] /packer-build-windows through packer-build-windows_30 along with a number of other builds. All of these have the one floppy left behind.

It looks like there was a fix in packer 1.2.4 to remove floppies from the remote server in vmware-esxi:
builder/vmware-esxi: Remove floppy files from the remote server on cleanup. [GH-6206] (https://github.com/hashicorp/packer/pull/6206). Is something similar needed? 

vsphere: 6.0 U3
Packer 1.2.5
packer-builder-vsphere 2.0

**Comment by signed8bit** [comment]
I am seeing the same thing.

vsphere 6.5
Packer 1.3.1
packer-builder-vsphere 2.0
