### ISSUE TITLE
Build 'vsphere-iso' errored: error creating vm: resource pool 'esxi1.example.com/Resources/' not found

### ISSUE THREAD

**Issue by aiuex79** [jetbrains-infra/packer-builder-vsphere#140]
We don't resource pools. I tried adding the cluster name, that reported host not found.  Any ideas?  I'm running this build.  https://github.com/jetbrains-infra/packer-builder-vsphere/releases  I'm running as root on my RHEL 7.2 machine (it's a lab)

==> vsphere-iso: Creating VM...
Build 'vsphere-iso' errored: error creating vm: resource pool 'esxi1.example.com/Resources/' not found

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error creating vm: resource pool 'esi1.example.com/Resources/' not found

==> Builds finished but no artifacts were created.

Trying to use the ubuntu example against 6.5 and 6.7 vsphere.

{
  "builders": [
    {
      "type": "vsphere-iso",

      "vcenter_server":      "vc1.ss.local",
      "username":            "administrator@vsphere.local",
      "password":            "workieplease",
      "insecure_connection": "true",

      "vm_name": "example-ubuntu",
      "host":     "esxi1.ss.local",
      "guest_os_type": "ubuntu64Guest",
      "ssh_username": "root",
      "ssh_password": "workieplease",

      "CPUs":             1,
      "RAM":              1024,
      "RAM_reserve_all": true,

      "disk_controller_type":  "pvscsi",
      "disk_size":        32768,
      "disk_thin_provisioned": true,

      "network_card": "vmxnet3",

      "iso_paths": [
        "NFS-ISO/ubuntu-16.04.5-server-amd64.iso"
      ],
      "floppy_files": [
        "{{template_dir}}/preseed.cfg"
      ],
      "boot_command": [
        "<enter><wait><f6><wait><esc><wait>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
        "<bs><bs><bs>",
        "/install/vmlinuz",
        " initrd=/install/initrd.gz",
        " priority=critical",
        " locale=en_US",
        " file=/media/preseed.cfg",
        "<enter>"
      ]
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "inline": ["ls /"]
    }
  ]
}

**Comment by aiuex79** [comment]
figured out.

**Comment by EricWang8230** [comment]
@aiuex79  could you share your idea?
Thanks.

Eric

**Comment by kathirmarx88** [comment]
@aiuex79 Could you share what did you do to fix the issue?

**Comment by BlackestDawn** [comment]
@aiuex79 Please, could you share what you did to fix this? I have tried every other potential solution I could find but still nothing. If yours is different I would like to try it as well.

**Comment by daxgames** [comment]
@aiuex79 Can you please share your solution to this?

**Comment by AshwinSarimin** [comment]
Come on man also provide the solution if you have it figured out @aiuex79

**Comment by alfonzso** [comment]
I have same problem, and I solved with adding this: `"cluster": "<ADD_CLUSTER_NAME>",`
