### ISSUE TITLE
Waiting for IP...

### ISSUE THREAD

**Issue by steveschofield** [jetbrains-infra/packer-builder-vsphere#141]
Getting a Waiting on IP address error using vsphere-iso provider.  Using the latest build of the linux.

- vSphere 6.7, user has admin perms in vCenter
- DHCP network available on port group, tested and addresses are being retrieved by other machines.
- Packer being run on RHEL 7.2 machine as root
- No firewalls
- Can't see console since no tools are installed
- ISO of kickstart, and CentOS are on local vsanDatastore 
- my kickstart file is from here https://github.com/jetbrains-infra/packer-builder-vsphere/issues/124

[packer591098428.log](https://github.com/jetbrains-infra/packer-builder-vsphere/files/2312200/packer591098428.log)
[packer-log072314780.log](https://github.com/jetbrains-infra/packer-builder-vsphere/files/2312201/packer-log072314780.log)

**Comment by aiuex79** [comment]
I found a PXE boot for SCCM scope option overriding.  Will close for now, I'm getting an IP from DHCP server, need to adjust scope options
