### ISSUE TITLE
Feature Request provisioners loop

### ISSUE THREAD

**Issue by agowa338** [jetbrains-infra/packer-builder-vsphere#145]
Currently there is no loop in inside of the provisioners block, with this ticket I want to request having the possibility to write something like:

```
"provisioners": [
  {
    "type": "DoUntilFileExists",
    "check_file": "C:/Windows/Temp/DoUntilUpdateCompleteCheck"
    "provisioners": [
      {
        "type": "powershell",
        "execute_command": "$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue';. {{.Vars}};. {{.Path}}; exit $LastExitCode",
        "script": "./scripts/Install-WindowsUpdates.ps1"
      },
      {
        "type": "windows-restart"
      }
    ]
  }
]
```

## Example
when handling windows servers, there are cases when one does not know how often to restart the server, as it could be 3-4 or even 10 times. Therefore I want to have something that loops the script until a break condition is met (like look until a file exists or a separate check script returns a specific exit code)

Currently I've to use this workaround:

```
"provisioners": [
{
    "type": "shell",
    "execute_command": "$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue';Invoke-Expression -Command (Get-Content -Path '{{.Path}}' -Raw); exit $LastExitCode",
    "skip_clean": true,
    "remote_folder": "C:/Windows/Temp",
    "expect_disconnect": true,
    "script": "./scripts/Install-WindowsUpdates.ps1"
  },
  {
    "type": "shell",
    "pause_before": "60m",
    "start_retry_timeout": "60m",
    "remote_folder": "C:/Windows/Temp",
    "skip_clean": true,
    "execute_command": "$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue';Invoke-Expression -Command (Get-Content -Path '{{.Path}}' -Raw); exit $LastExitCode",
    "script": "./scripts/Start-CleanUp.ps1"
  },
]
```

this workaround has the following problems:
 - The Install-WindowsUpdates.ps1 Skript is rebooting the server, leading to packer loosing connection
 - Packer does not know if the Updates already completed or if the server reboots once more.
 - Currently the next task requires a "pause_before" step, but it is not known if the former script already finished, or if it is still installing updates
 - the powershell executor cannot be used as it is missing "pause_before", "skip_clean" and "expect_disconnect" functionality like used in the above workaround.

**Comment by VladRassokhin** [comment]
I'd say that should be feature request for [Packer](https://github.com/hashicorp/packer) itself

**Comment by agowa338** [comment]
oh, sorry, that was the wrong repository...
