### ISSUE TITLE
Option needed to not set boot order

### ISSUE THREAD

**Issue by seandilda** [jetbrains-infra/packer-builder-vsphere#149]
We are having a problem with our VMs generated through this plugin.   When they are exported as OVF and reimported, VMware fails to load them.  After digging around, this is because they have a &lt;vmw:BootOrderSection&gt; section in the OVF.  This comes from the fact that packer-builder-vsphere is setting the boot order via the vSphere API.
The OVF process works fine if I unset the boot order before doing the OVF export.

In order to support this, can we have an option to unset the boot order at the end of the process, or not set it at all?  It looks like it was possible to not set the boot order up until commit e59c1326f96aa49976a63a70f1252c59ab093cf0

**Comment by chitashvili** [comment]
Hello, I faced same issue and I added following in mu Jenkins pipeline to get it work properly:
1. I reset boot options by govc: /usr/local/bin/govc device.boot -u ${USERNAME}:${PASSWORD}@${VCENTER} -vm ${VM_NAME} -order -
2. I do export with ovftool  and after all imports back to vCloud or vCenter works without any issues.

I know it does not fix plugin functionality but maybe can be handy.

**Comment by mkuzmin** [comment]
please test binaries from PR
https://teamcity.jetbrains.com/viewLog.html?buildTypeId=PackerVSphere_Build&buildId=lastFinished&buildBranch=boot-order&tab=artifacts
