### ISSUE TITLE
WinRM no_proxy environment variable

### ISSUE THREAD

**Issue by IcedGoblin** [jetbrains-infra/packer-builder-vsphere#150]
We are having an issue with WinRM connectivity. It appears that Packer is trying to use the proxy server set in `http_proxy` environment variable. As such we have tried adding the IP address, wildcard IP range and IP range in CIDR format to `no_proxy` but have been unable to get it to connect without removing the `http_proxy` variable completely.

I have seen other suggestions [here](https://github.com/hashicorp/packer/issues/5725) and [here](https://github.com/hashicorp/packer/issues/4857) regarding setting `winrm_no_proxy` and `ssh_interface` however these seem to be invalid options.

Does anyone know any other ways to honor the `no_proxy` setting or whether I have missed something in trying the other options?

**Comment by theemptyone** [comment]
I ran into this as well, and have posted this on the google groups mailing list:

https://groups.google.com/forum/#!topic/packer-tool/SK2-TOwez5o

**Comment by mkuzmin** [comment]
Provisioner logic is not specific to builders. Please report it to the core Packer project.
