### ISSUE TITLE
Overwrite VM or template parameter

### ISSUE THREAD

**Issue by segator** [jetbrains-infra/packer-builder-vsphere#158]
a parameter that deletes old template or VM with the setted name and recreate it with the new one.

other solution will be if this action is done by post-processor, so only template is replaced if the build is correct. For exemple
VM-Name: coreos-latest
vsphere-iso create vm coreos-latest-12321321
deploy succesfully then post-procesor detect coreos-latest already exist then delete it and rename
coreos-latest-12321321 to coreos-latest.

**Comment by mkuzmin** [comment]
Suggested in #50
