### ISSUE TITLE
communicator as none causes the build to fail

### ISSUE THREAD

**Issue by riponbanik** [jetbrains-infra/packer-builder-vsphere#168]
Using communication as "none" causes the build to fail. Tried with different version of packer  - 0.12.2, 1.1.3 and 1.30.0. using vsphere-iso version 2.0

2018/10/17 16:13:40 packer.exe: 2018/10/17 16:13:40 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2018/10/17 16:13:40 packer.exe: 2018/10/17 16:13:40 Setting cache directory: C:\Workspace\xxx\packer-build\packer_cache
2018/10/17 16:13:40 packer.exe: 2018/10/17 16:13:40 args: []string{"packer-post-processor-vagrant"}
2018/10/17 16:13:40 packer.exe: 2018/10/17 16:13:40 Plugin minimum port: 10000
2018/10/17 16:13:40 packer.exe: 2018/10/17 16:13:40 Plugin maximum port: 25000
2018/10/17 16:13:40 packer.exe: 2018/10/17 16:13:40 Plugin address: tcp 127.0.0.1:10000
2018/10/17 16:13:40 packer.exe: 2018/10/17 16:13:40 Waiting for connection...
2018/10/17 16:13:40 packer.exe: 2018/10/17 16:13:40 Serving a plugin connection...
2018/10/17 16:13:40 Build debug mode: false
2018/10/17 16:13:40 Force build: false
2018/10/17 16:13:40 On error:
2018/10/17 16:13:40 Preparing build: centos-75-vsphere
2018/10/17 16:13:40 Waiting on builds to complete...
2018/10/17 16:13:40 Starting build run: centos-75-vsphere
2018/10/17 16:13:40 Running builder: vsphere-iso
2018/10/17 16:13:40 [INFO] (telemetry) Starting builder vsphere-iso
==> centos-75-vsphere: Creating VM...
==> centos-75-vsphere: Customizing hardware...
2018/10/17 16:13:41 [INFO] (telemetry) ending vsphere-iso
==> centos-75-vsphere: Running post-processor: vagrant
2018/10/17 16:13:41 [INFO] (telemetry) Starting post-processor vagrant
2018/10/17 16:13:41 [INFO] (telemetry) ending vagrant
2018/10/17 16:13:41 Deleting original artifact for build 'centos-75-vsphere'
2018/10/17 16:13:41 ui error: Build 'centos-75-vsphere' errored: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type, can't build box: jetbrains.vsphere
Build 'centos-75-vsphere' errored: 1 error(s) occurred:
2018/10/17 16:13:41 Builds completed. Waiting on interrupt barrier...
2018/10/17 16:13:41 machine readable: error-count []string{"1"}
2018/10/17 16:13:41 ui error:

==> Some builds didn't complete successfully and had errors:
* Post-processor failed: Unknown artifact type, can't build box: jetbrains.vsphere
2018/10/17 16:13:41 machine readable: centos-75-vsphere,error []string{"1 error(s) occurred:\n\n* Post-processor failed: Unknown artifact type, can't build box: jetbrains.vsphere"}

2018/10/17 16:13:41 ui error: --> centos-75-vsphere: 1 error(s) occurred:
==> Some builds didn't complete successfully and had errors:

--> centos-75-vsphere: 1 error(s) occurred:
* Post-processor failed: Unknown artifact type, can't build box: jetbrains.vsphere

==> Builds finished but no artifacts were created.
2018/10/17 16:13:41 [INFO] (telemetry) Finalizing.
* Post-processor failed: Unknown artifact type, can't build box: jetbrains.vsphere

==> Builds finished but no artifacts were created.
2018/10/17 16:13:43 waiting for all plugin processes to complete...
2018/10/17 16:13:43 c:\tools\packer\1.3.0\packer.exe: plugin process exited
2018/10/17 16:13:43 c:\tools\packer\1.3.0\packer.exe: plugin process exited
2018/10/17 16:13:43 c:\tools\packer\1.3.0\packer-builder-vsphere-iso.exe: plugin process exited

**Comment by mkuzmin** [comment]
`vagrant` post-processor is not compatible with this builder. What result do you expect?

**Comment by riponbanik** [comment]
@mkuzmin i have tried removing it as well, but it fails to create vm with the following error -

2018/10/18 08:48:51 Setting cache directory: C:\Workspace\tcorp\automation\packer-build\packer_cache
2018/10/18 08:48:51 Loading builder: vsphere-iso
2018/10/18 08:48:51 Creating plugin client for path: c:\tools\packer\1.3.0\packer-builder-vsphere-iso.exe
2018/10/18 08:48:51 Starting plugin: c:\tools\packer\1.3.0\packer-builder-vsphere-iso.exe []string{"c:\\tools\\packer\\1.3.0\\packer-builder-vsphere-iso.exe"}
2018/10/18 08:48:51 Waiting for RPC address for: c:\tools\packer\1.3.0\packer-builder-vsphere-iso.exe
2018/10/18 08:48:51 packer-builder-vsphere-iso.exe: 2018/10/18 08:48:51 Plugin minimum port: 10000
2018/10/18 08:48:51 packer-builder-vsphere-iso.exe: 2018/10/18 08:48:51 Plugin maximum port: 25000
2018/10/18 08:48:51 packer-builder-vsphere-iso.exe: 2018/10/18 08:48:51 Plugin address: tcp 127.0.0.1:10000
2018/10/18 08:48:51 packer-builder-vsphere-iso.exe: 2018/10/18 08:48:51 Waiting for connection...
2018/10/18 08:48:51 packer-builder-vsphere-iso.exe: 2018/10/18 08:48:51 Serving a plugin connection...
2018/10/18 08:48:51 Loading provisioner: shell
2018/10/18 08:48:51 Plugin could not be found. Checking same directory as executable.
2018/10/18 08:48:51 Current exe path: c:\tools\packer\1.3.0\packer.exe
2018/10/18 08:48:51 Creating plugin client for path: c:\tools\packer\1.3.0\packer.exe
2018/10/18 08:48:51 Starting plugin: c:\tools\packer\1.3.0\packer.exe []string{"c:\\tools\\packer\\1.3.0\\packer.exe", "plugin", "packer-provisioner-shell"}
2018/10/18 08:48:51 Waiting for RPC address for: c:\tools\packer\1.3.0\packer.exe
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 [INFO] Packer version: 1.3.0
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 Packer Target OS/Arch: windows amd64
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 Built with Go Version: go1.11
centos-75-vsphere output will be in this color.
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 Attempting to open config file: C:\Users\riponb\AppData\Roaming\packer.config

2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 [WARN] Config file doesn't exist: C:\Users\riponb\AppData\Roaming\packer.config
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 Setting cache directory: C:\Workspace\tcorp\automation\packer-build\packer_cache
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 args: []string{"packer-provisioner-shell"}
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 Plugin minimum port: 10000
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 Plugin maximum port: 25000
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 Plugin address: tcp 127.0.0.1:10000
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 Waiting for connection...
2018/10/18 08:48:51 packer.exe: 2018/10/18 08:48:51 Serving a plugin connection...
2018/10/18 08:48:51 Build debug mode: false
2018/10/18 08:48:51 Force build: false
2018/10/18 08:48:51 On error:
2018/10/18 08:48:51 Preparing build: centos-75-vsphere
2018/10/18 08:48:51 Waiting on builds to complete...
2018/10/18 08:48:51 Starting build run: centos-75-vsphere
2018/10/18 08:48:51 Running builder: vsphere-iso
2018/10/18 08:48:51 [INFO] (telemetry) Starting builder vsphere-iso
==> centos-75-vsphere: Creating VM...
==> centos-75-vsphere: Customizing hardware...
2018/10/18 08:48:55 [INFO] (telemetry) ending vsphere-iso
2018/10/18 08:48:55 Builds completed. Waiting on interrupt barrier...
==> Builds finished. The artifacts of successful builds are:
2018/10/18 08:48:55 machine readable: centos-75-vsphere,artifact-count []string{"1"}
Build 'centos-75-vsphere' finished.
2018/10/18 08:48:55 machine readable: centos-75-vsphere,artifact []string{"0", "builder-id", "jetbrains.vsphere"}

**Comment by mkuzmin** [comment]
I don't see any errors here

**Comment by riponbanik** [comment]
it creates the box and does not boot from iso.

**Comment by riponbanik** [comment]
@mkuzmin in other packer builders it means bootstrap the machine (either via autounattend,kickstart, pressed etc) but do not run any provisioner. As @eric-gunn mentioned, we may just need to build the machine in isolated environment where we cannot have any winrm/ssh connection to the machine. By the way do you have any working example of autounattend for vm tools installation in windows? Thanks.

**Comment by mkuzmin** [comment]
Windows example in https://github.com/jetbrains-infra/packer-builder-vsphere/tree/master/examples/windows

Let's continue this discussion in #169. I'm interested to hear use cases why people need VMs with disabled WinRM.

**Comment by riponbanik** [comment]
@mkuzmin  Thanks a lot
