### ISSUE TITLE
Using disk_additional_size parameter in vsphere-iso

### ISSUE THREAD

**Issue by smutel** [jetbrains-infra/packer-builder-vsphere#171]
Hello,

I would like to use the disk_additional_size parameter (https://www.packer.io/docs/builders/vmware-iso.html#disk_additional_size) to build vsphere template with multiple disks but it seem to not work properly. I am using the last version of packer (1.3.1) and the last version of vsphere-builder (2.0.1). Did I miss something ?

```
disk_size:            48000,
disk_additional_size: [4000],
```

```
vsphere output will be in this color.

1 error occurred:

* unknown configuration key: "disk_additional_size"
```

Thanks.

**Comment by mkuzmin** [comment]
that's absolutely different builder. they share neither code nor parameter naming.

the feature request in #68, PR in #113
