### ISSUE TITLE
New VM from template: Guest customization failing

### ISSUE THREAD

**Issue by Boran** [jetbrains-infra/packer-builder-vsphere#178]
Hi,

I create a VM for Debian 9 using packer+vsphere-iso  (ISO+preseed), the VM install works fine.
- The open-vm-tools package is installed and is recognised by vSphere.
- SSH file/shell provisioners work fine (for post install config)

However after stopping the VM, converting to a template and launching a VM from the template customizations are refused (all from the UI).
"Customization of the guest operating system is not supported in this configuration... Operating System: Debian GNU/Linux 9 (64-bit)"

The VM is created and used on ESX 6.5, it has the correct hw version(13), and guest os=Linux/Debian8_64 and Debian9_64 has been tried.
So it does not seem like a mismatch been ESX version and Guestos, or virtual hw version.
Its not even clear to me if this is an vsphere-iso issue.

Any tips on how to dig deeper?

**Comment by mkuzmin** [comment]
check version of VMware Tools. Previousl yopen-vm-tools didn't include customization plugin.
Check logs inide a guest VM in `/var/log/vmware-imc/toolsDeployPkg.log`

**Comment by t3mi** [comment]
VMware customization relies on perl to be present for customization of Linux boxes inside the vm. Check if you have it installed as part of the template creation process.

**Comment by Boran** [comment]
Perl is installed (probably as a dependency). 
vSphere sees "version:10277 "
open-vm-tools is deb package 2.10.1.5-5055683.1+deb9u1

there is no /var/log/vmware-im*
There is a file vmware-vmsvc.log which shows plugins being loaded and power off/on events, but no errors.

**Comment by mkuzmin** [comment]
I'd check in [VMware forums](https://communities.vmware.com/community/vmtn/vsphere/). This issue is not specific to Packer, you can find a much broader community there.

**Comment by Boran** [comment]
Fixed: use guest_os_type=ubuntu64Guest (even with Debian).
Also discovred /var/log/vmware-imc/toolsDeployPkg.log, which can help.

**Comment by Boran** [comment]
Also, see http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf , where there is no mention of Debian.
