### ISSUE TITLE
Packer run failures after modifications to keyboard on MacOS

### ISSUE THREAD

**Issue by mdunnsl** [jetbrains-infra/packer-builder-vsphere#191]
This may likely be a fusion or macos issue, but perhaps someone has run into this.

I run Packer on my Mac, and that machine has multiple languages configured (English and Japanese). The other day I went and modified my keyboard settings (removing Japanese), and this has caused havoc in my Packer builds. See gist: https://gist.github.com/mdunnsl/c89dfddeac251fe9a624f6631d9f2d0d

Specifically I'm seeing this line `GetInputSourceEnabledPrefs user file path = /Users/MYUSERNAME/Library/Preferences/com.apple.HIToolbox.plist` which seems to be the file that defines these input configurations. I have read that when this is misconfigured to delete it and reboot, which I did to no avail. I have fully purged VMWare Fusion per their instructions and re-installed it to no avail.

I'm at a point where I will likely have to do a time machine restore otherwise (and never mess with my language settings again).

OS: macOS Mojave 10.14
VMWare Fusion 10.1.4
Packer 1.3.2

**Comment by mkuzmin** [comment]
This is the repo for external vSphere plugin. Report your issue to core Packer project.
