### ISSUE TITLE
"host '' not found" on floppy upload to DRS cluster

### ISSUE THREAD

**Issue by moneycat** [jetbrains-infra/packer-builder-vsphere#202]
There is an error that aborting packer build after upgrading vsphere-iso plug-in to version 2.2. Here are stdout messages:
```
vsphere-iso output will be in this color.

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mount ISO images...
==> vsphere-iso: Creating floppy disk...
    vsphere-iso: Copying files flatly from floppy_files
    vsphere-iso: Copying file: ubuntu-ezs3.seed
    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : []
    vsphere-iso: Done copying paths from floppy_dirs
==> vsphere-iso: Uploading created floppy image
==> vsphere-iso: Destroying VM...
Build 'vsphere-iso' errored: host '' not found
```

On the other hand, Packer v1.3.2/v1.3.3 + vsphere-iso v2.1 work fine.

**Comment by thor** [comment]
See #183.

**Comment by moneycat** [comment]
Hi @thor 
In #183 it says if "datastore" or "network" are NOT specified explicitly, the error raises. However, in our configuration file, we've specified the fields in "builders", as comments below the issue:

> "datastore": "Intel_....",
> ...
> "network": "DPortGroup....",

**Comment by theonlydude1** [comment]
Hi,
Same on my side, after upgraded to version 2.2 I've the error: vsphere-iso: host '' not found even if I've specified a cluster, a datastore and a network

**Comment by gwesterfieldjr** [comment]
I'm seeing similar issue to this except error is just a 404

    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : []
    vsphere-iso: Done copying paths from floppy_dirs
==> vsphere-iso: Uploading created floppy image
==> vsphere-iso: Destroying VM...
Build 'vsphere-iso' errored: 404 Not Found

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: 404 Not Found

Any ideas?

**Comment by tmmruk** [comment]
I am seeing the same problem as @gwesterfieldjr in packer 1.5.4 when trying to set granular permissions. Any further update on what permissions are required to resolve this?

**Comment by sporokh** [comment]
Same here, using Packer 1.5.4 and vsphere-iso builder, getting "404 not found" while uploading the floppy.
@tmmruk did you believe it's related to permissions?
