### ISSUE TITLE
floppy_files: floppy creation failed with timeout

### ISSUE THREAD

**Issue by Boeller666** [jetbrains-infra/packer-builder-vsphere#204]
```
==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mount ISO images...
==> vsphere-iso: Creating floppy disk...
    vsphere-iso: Copying files flatly from floppy_files
    vsphere-iso: Copying file: C:\Users\rgaertner\Repos\DevOps\Packer-Templates\CentOS/ks.cfg
    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : []
    vsphere-iso: Done copying paths from floppy_dirs
==> vsphere-iso: Uploading created floppy image
==> vsphere-iso: Destroying VM...
Build 'vsphere-iso' errored: Put https://x.x.x.x/folder/SWE-DevOps-Team_CentOS_7_5_minimal/packer-tmp-created-floppy.flp?dsName=MY_DS: dial tcp x.x.x.x:443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: Put https://x.x.x.x/folder/SWE-DevOps-Team_CentOS_7_5_minimal/packer-tmp-created-floppy.flp?dsName=MY_DS: dial tcp x.x.x.x:443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.

==> Builds finished but no artifacts were created.
```

(IP and datastore name changed for security reasons!)

Seems that packer created the floppy image but can't upload it. I can also see the VM shortly before it's deleted when the error occurs. Any idea what could cause this issue? Write permissions? But VM files are created inside the folder "SWE-DevOps-Team_CentOS_7_5_minimal" in the datastore.

---
Packer v1.3.3
packer-builder-vsphere-iso.exe v2.3

**Comment by spstratis** [comment]
Did you ever figure out the cause of this?

**Comment by spstratis** [comment]
I'm running into the same exact issue. Trying to determine if it's permissions or something else

**Comment by bwood42** [comment]
Ran into this issue as well.  We created a Provisioning Role with specific permissions, including the recommended floppy related ones, but weren't able to copy the floppy image up.  We then gave the account pure Administrator role and it copied up fine.  Now we've got to go back and pare the permissions down till we figure it out.

**Comment by SvenKo** [comment]
I currently have the same problem. Have you already found a solution? Maybe Firewall?!?!

**Comment by nitrocode** [comment]
It's definitely missing some permission because it works for our admin user just not the least privilege user with the perms from the README

**Comment by nitrocode** [comment]
@mkuzmin saw you put the perms in the readme 10 months ago. Is there another perm? I'm on vsphere esxi 6.7
