### ISSUE TITLE
Multiple builders of the same type

### ISSUE THREAD

**Issue by bhundven** [jetbrains-infra/packer-builder-vsphere#207]
I have two `vsphere-iso` builders in my packer build, and the build fails with:

```
Failed to parse template: 1 error(s) occurred:

* builder 2: builder with name 'vsphere-iso' already exists
ERROR: Job failed: command terminated with exit code 1
```

with a json file with something like:
```
  "builders": [
    {
      "type": "vsphere-iso",
      "vm_name: "vm1",
      ... more options set...
    },
    {
      "type": "vsphere-iso",
      "vm_name: "vm2",
      ... more options set...
    }
```

**Comment by bhundven** [comment]
So if you don't set `name` the name of the builder falls back to the build type. I'd think it would fall back to the `vm_name` instead.

**Comment by VladRassokhin** [comment]
That's not packer-builder-vsphere specific problem, packer just not allows to have two builders of the same type without different names, that happens prior to any code in plugin executed, so won't fix. https://github.com/hashicorp/packer/blob/HEAD/template/parse.go#L85L111
