### ISSUE TITLE
winrm timeout

### ISSUE THREAD

**Issue by rismoney** [jetbrains-infra/packer-builder-vsphere#212]
for long running builds > 2h, this is needed.

**Comment by rismoney** [comment]
looks like this param can be used as it looks to be inherited from communicator helper.  just not documented here.  testing it out.

**Comment by codyja** [comment]
@rismoney So is there an option that works here?

**Comment by rismoney** [comment]
`"winrm_timeout": "4h"`

I believe this works.  can close.

**Comment by VladRassokhin** [comment]
Connectors is not scope of this plugin, they're provided by Packer itself and all configs are the same.
[Here's documentation about connectors](https://www.packer.io/docs/templates/communicator.html)
