### ISSUE TITLE
Template issue

### ISSUE THREAD

**Issue by anoopkbaby1** [jetbrains-infra/packer-builder-vsphere#213]
Hi,

     I am trying to spin a VM in ESX cluster using packer. But I didn't get much idea from packer site. While I am google, I noticed this plugin and I just installed go and dep, then downloaded packer-builder-vsphere-clone into packer folder. Then created following json file on same location : 

{
  "builders": [
    {
        "type": "vsphere-clone",

        "vcenter_server": "xx.com",
        "insecure_connection": "true",
        "username": "username",
        "password": "password",
        "cluster": "cluster name",
        "host": "vcenter url",
        "datacenter": "datacenter name",
        "vm_name":  "packer-esx",
        "convert_to_template": "true",
        "folder": "WIP",
        "ssh_username": "not sure what it should be",
        "template": "[CM-12-19-3PAR] CM-win2k12r2-template/CM-win2k12r2-template.vmxi"
    }
  ]
}

but while I am running : 

packer build esx.json

getting the below error : 

vsphere-clone output will be in this color.

==> vsphere-clone: Cloning VM...
Build 'vsphere-clone' errored: vm '[CM-12-19-3PAR] CM-win2k12r2-template/CM-win2k12r2-template.vmxi' not found

==> Some builds didn't complete successfully and had errors:
--> vsphere-clone: vm '[CM-12-19-3PAR] CM-win2k12r2-template/CM-win2k12r2-template.vmxi' not found

==> Builds finished but no artifacts were created.

Any help on this really appreciated

Anoop

**Comment by mkuzmin** [comment]
`template` parameter should contain VM name from inventory, not a filename in a datastore.
Try `CM-win2k12r2-template` instead.

**Comment by anoopkbaby1** [comment]
Now another issue. I am trying to clone a windows machine. The build expecting a ssh_username 👍 
* An ssh_username must be specified
  Note: some builders used to default ssh_username to "root".

As its a windown OS , I am wondering what should be the SSH User parameter.

**Comment by anoopkbaby1** [comment]
wow that helped. Thanks mkuzmin
