### ISSUE TITLE
ISOs not connected on boot

### ISSUE THREAD

**Issue by stobias123** [jetbrains-infra/packer-builder-vsphere#223]
When using two ISOs following the windows 8 example, the ISOs aren't mounted. They show connect on boot, but never connect.. not sure what I'm missing.

The floppy connects fine.
```
{
  "builders": [
    {
      "type": "vsphere-iso",
      "vcenter_server": "",
      "cluster": "CLUSTER",
      "network": "NETWORK",
      "datacenter": "DATACENTER",
      "datastore": "DATASTORE",
      "username": "USERNAME",
      "password": "PASSWORD",
      "insecure_connection": "true",
      "vm_name": "win2012r2-packer",
      "guest_os_type": "windows8Server64Guest",
      "communicator": "winrm",
      "winrm_username": "admin",
      "winrm_password": "admin",
      "CPUs": 4,
      "RAM": 8192,
      "disk_controller_type": "pvscsi",
      "disk_size": 32768,
      "disk_thin_provisioned": true,
      "network_card": "vmxnet3",
      "iso_paths": [
        "[DATASTORE] ISO's/iso/microsoft/windows2012/en_windows_server_2012_r2_vl_x64_dvd_3319595.iso",
        "[DATASTORE] ISO's/iso/vmware/2012_r2_vmware_tools_windows.iso"
      ],
      "floppy_files": [
        "{{template_dir}}/files/"
      ],
      "floppy_img_path": "[DATASTORE] ISO's/iso/vmware/pvscsi-Windows8.flp"
    }
  ],
  "provisioners": [
    {
      "type": "windows-shell",
      "inline": [
        "dir c:\\"
      ]
    }
  ]
}
```

**Comment by LIV2** [comment]
This is usually because the url's to the ISOs are incorrect. I believe that is the case for you
```
      "iso_paths": [
        "[]ISO's/iso/microsoft/windows2012/en_windows_server_2012_r2_vl_x64_dvd_3319595.iso",
        "[]ISO's/iso/vmware/2012_r2_vmware_tools_windows.iso"
      ],
```
Should instead be
```
      "iso_paths": [
        "[ISO's] /iso/microsoft/windows2012/en_windows_server_2012_r2_vl_x64_dvd_3319595.iso",
        "[ISO's] /iso/vmware/2012_r2_vmware_tools_windows.iso"
      ],
```

**Comment by stobias123** [comment]
@LIV2  - Sorry for the delayed response. I censored names of the datastores. everything outside brackets are folders.

ISOs are available when I view in "edit settings"- but not connected. Boot goes all the way through to pxe.

**Comment by LIV2** [comment]
@stobias123 if you tick "Connected" and apply the change does it work?

If not it means something is wrong with the path given, in this case edit the VM settings to mount the ISO then take note of the path it shows in the settings pane. I think you'll find you don't need the leading / which might also be why it doesn't work

For instance on mine the iso_path I have is ```[ISOS] Linux/CentOS-7-x86_64-DVD-1804.iso```

**Comment by stobias123** [comment]
@LIV2  - I appreciate the responses. I'll double check ticking "conneted" when I get back into the office.

For the record however, there is no leading slash. 
```
"[DATASTORE] ISO's/iso/micr...
```
The edit settings dialog box also shows the correct ISO "in" the drive, it's just not "connected.

**Comment by JesseHermes** [comment]
I had this same issue, tried it against 2 different vCenters, a 6.5 and 6.7, both the VM was started iso path was specified, set to start connected,  but was disconnected.   After changing iso_paths to match the case exactly what is on the datastore, it fixed the issue.  (in the json file I had the file extension '.iso' but on the datstore it was all caps)  Same behavior if I change case in the file name to be different than the file on the datastore. 

However, changing the case did not have an effect on the validation (like would happen if I specified an ISO which was not present on the datastore. ) so everything appears correct to the user.

It would be helpful to update the documentation to call out that iso_paths is case sensitive, or validate that the case specified matches exactly what's on the datastore, as it may not be obvious to all users.

**Comment by stobias123** [comment]
@LIV2  - Sorry I didn't get back to you... Looks like I had the path messed up. Wish there was a validation, but beggars can't be choosers 🤷‍♂ 

Thanks!
