### ISSUE TITLE
Type of Post-Processor

### ISSUE THREAD

**Issue by G3ph4z** [jetbrains-infra/packer-builder-vsphere#231]
The doc is mentions this parameter:

> convert_to_template(boolean) - Convert VM to a template. Defaults to false.

I would like to use it (of course), but I can't find what is the type of post-processor?
It doesn't work with "vsphere-iso", like this:
```
   "post-processors": [
    {
	"type":"vsphere-iso",
	"convert_to_template": true
    }
  ]
```

**Comment by VladRassokhin** [comment]
It's not a post-processor nor it option. 'convert_to_template' is option of both 'vmware-iso' and 'vmware-clone' builders

**Comment by G3ph4z** [comment]
@VladRassokhin so its supposed to be an option for builder?
