### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by bhundven** [jetbrains-infra/packer-builder-vsphere#248]
@mkuzmin has not made a release since January, there are 13 Pull Requests in various states, and with this ticket 68 issues open, and is now breaking compatibility with newer versions of packer.

If you don't have time to continue to work on this project, should we fork this and maintain it elsewhere. Would someone have time to step up and maintain for the long term to trying to upstream this into packer itself?

**Comment by gstorme** [comment]
They are already in the process of merging this into packer.
https://github.com/hashicorp/packer/pull/7168

**Comment by bhundven** [comment]
Oh, rad. I guess I should have looked before posting this... I'll close this.
