### ISSUE TITLE
unknown configuration key: "ip_settle_timeout"

### ISSUE THREAD

**Issue by Nevynxxx** [jetbrains-infra/packer-builder-vsphere#257]
Hi,

  I'm getting the issue where creating a vsphere vm gets an IPv6 address which packer then tries to use to bind to, eventually timing out and failing.

  As per #230 I have tried setting the system to not use IPv6 (setting the registry key to 255, 16, and 32 which are the microsoft values defined https://support.microsoft.com/en-gb/help/929852/guidance-for-configuring-ipv6-in-windows-for-advanced-users.

  I have tried using "ip_settle_timeout" which from the description should do what I want (wait until an IPv4 address is there and use that). But I get the error "unknown configuration key: "ip_settle_timeout"".

`c:\GitRepos\packer-windows>packer validate vsphere-2012r2.json
Template validation failed. Errors are shown below.

Errors validating build 'vsphere-iso'. 1 error(s) occurred:

* unknown configuration key: "ip_settle_timeout"

c:\GitRepos\packer-windows>dir
 Volume in drive C has no label.
 Volume Serial Number is 6606-9E49

 Directory of c:\GitRepos\packer-windows

01/08/2019  14:48    <DIR>          .
01/08/2019  14:48    <DIR>          ..
19/06/2019  10:57                47 .gitignore
01/08/2019  14:27        36,648,960 packer-builder-vsphere-iso.exe
01/08/2019  12:45    <DIR>          scripts
19/06/2019  10:54    <DIR>          setup
01/08/2019  14:25             1,742 vsphere-2012r2.json
               3 File(s)     36,650,749 bytes
               4 Dir(s)  489,860,644,864 bytes free

c:\GitRepos\packer-windows>packer version
Packer v1.4.2

c:\GitRepos\packer-windows>`

Please help.

**Comment by VladRassokhin** [comment]
That's because version with 'ip_settle_timeout' is not released yet. You can [download nightly build from CI server](https://teamcity.jetbrains.com/viewLog.html?buildId=2425975&buildTypeId=PackerVSphere_Build&tab=artifacts) (ignore red state if build)

**Comment by nslracer** [comment]
Thank you for all the work on this great tool. Is there an ETA on 2.4?
