### ISSUE TITLE
Windows vms build remain with 2 CDroms

### ISSUE THREAD

**Issue by p0w3rb0y** [jetbrains-infra/packer-builder-vsphere#259]
Hi,
If you setup a windows vm usually you need to create 2 cdroms to mount the Windows and vmware tools ISO.
I can't see an option to remove one of the cdroms when the provisioning ends.
Is this possible?

**Comment by terbolous** [comment]
Fixed in PR #238, awaiting merge

**Comment by Roxyrob** [comment]
Hi,
remove_cdrom seems to removes "all CD-Rom drives". Is it possible to remove only specific drive (e.g. second drive, or specificed with a drive letter like "e" ) ? Without this param it is necessary to use something like powershell/powercli command to change VM configuration.

**Comment by VladRassokhin** [comment]
@Roxyrob please open issue in [Packer issue tracker](https://github.com/hashicorp/packer/issues), as now plugin part of Packer.

Closing as #238 was merged in latest Packer
