### ISSUE TITLE
packer-builder-vsphere-iso.linux unknown configuration key: "disk_additional_size"

### ISSUE THREAD

**Issue by darthVikes** [jetbrains-infra/packer-builder-vsphere#273]
Trying to build a centos7 vmware image using an ISO with multiple vmware drives.  

I know its supported with vmware-iso, but would like this as apart of the vsphere-iso builder tool.

from packers vmware-iso tool:
---------------------------------------------------------------
https://www.packer.io/docs/builders/vmware-iso.html

**Optional:**
disk_additional_size ([]uint) - The size(s) of any additional hard disks for the VM in megabytes. If this is not specified then the VM will only contain a primary hard disk. The builder uses expandable, not fixed-size virtual hard disks, so the actual file representing the disk will not use the full size unless it is full.
---------------------------------------------------------------

./packer build centos7.json
vsphere-iso output will be in this color.

1 error(s) occurred:

* unknown configuration key: "disk_additional_size"

[root@mnlxadmin packer]# ./packer -version
1.4.4

**Comment by VladRassokhin** [comment]
This plugin provides `vsphere-iso` and `vsphere-clone`, not `vmware-iso`. You're using docs from another packer plugin.
