### ISSUE TITLE
vsphere-iso: failed to load ks.cfg in RHEL 8 build

### ISSUE THREAD

**Issue by ericxnhu** [jetbrains-infra/packer-builder-vsphere#276]
Trying to use vspsher-iso to build a RHEL v8 template, the build failed at loading kickstart file. 

The terminal output  is like this:

==> rhel80-opcs-xfs-vsphere: Creating VM...
==> rhel80-opcs-xfs-vsphere: Customizing hardware...
==> rhel80-opcs-xfs-vsphere: Mount ISO images...
==> rhel80-opcs-xfs-vsphere: Creating floppy disk...
    rhel80-opcs-xfs-vsphere: Copying files flatly from floppy_files
    rhel80-opcs-xfs-vsphere: Copying file: ../centos/http/8/ks.cfg
    rhel80-opcs-xfs-vsphere: Done copying files from floppy_files
    rhel80-opcs-xfs-vsphere: Collecting paths from floppy_dirs
    rhel80-opcs-xfs-vsphere: Resulting paths from floppy_dirs : []
    rhel80-opcs-xfs-vsphere: Done copying paths from floppy_dirs
==> rhel80-opcs-xfs-vsphere: Uploading created floppy image
==> rhel80-opcs-xfs-vsphere: Adding generated Floppy...
==> rhel80-opcs-xfs-vsphere: Set boot order temporary...
==> rhel80-opcs-xfs-vsphere: Power on VM...
==> rhel80-opcs-xfs-vsphere: Waiting 10s for boot...
==> rhel80-opcs-xfs-vsphere: Typing boot command...
==> rhel80-opcs-xfs-vsphere: Waiting for IP...

On vm console I got the following:
"
**boot: linux inst.text inst.ks=hd:fd0:/ks.cfg
Loading ... failed: No such file or directory
boot:**
"
After a while it would go back to manual install screen.

My build json file is like this:
"........
"iso_paths": [
        "[{{ user `vsphere_datastore` }}] ISO/rhel-8.0-x86_64-dvd.iso"
      ],
      "floppy_files": [
        "../centos/http/8/ks.cfg"
      ],
      "boot_command": "<esc> <wait> linux inst.text inst.ks=hd:fd0:/ks.cfg <enter><wait>",
      "boot_wait": "10s",
      "convert_to_template": false
......"

The same json build file would work for rhel7.7 build: if I change "iso_paths" to "[{{ user `vsphere_datastore` }}] ISO/rhel-server-7.7-x86_64-dvd.iso", the build would go through.

Any thoughts?

**Comment by bhundven** [comment]
Rhel 8, and most newer distros don't have floppy support anymore. See the release notes.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.0_release_notes/index

This applys to centos 8 as well.

**Comment by ericxnhu** [comment]
Got it, thanks!

**Comment by ericxnhu** [comment]
So how to use vsphere-iso to build rhel 8 image? I tried placing the ks.cfg
on a nfs server, and pointing to it in boot command (like
install.ks=nfs:.../ks.cfg), but it still couldn't load the file.

Thanks in advance.

Eric

**Comment by Jammicus** [comment]
We stuck it on a http server, so first we defined which folder we have placed our kickstart in locally:

```  
   "http_directory": "http/kickstart",

```

Packer will then serve that directory and its contents on a http server. You can then in the boot command point to the http server and the kickstart using the following (Assuming your kickstart is called ks.cfg)

```
      "boot_command": [
        "<up><wait><tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort}}/ks.cfg <enter>"
      ]
```

**Comment by superghi64** [comment]
This HTTP way is working fine with RHEL 7.x. but anyone has done it with RHEL 8.x? because it's not working!!!

**Comment by snipervelli** [comment]
Same for me http is working  on CentOS 7 but not for CentOS 8.x. Can someone please post any working examples of their boot command. Or if anything was done to their KS file.

**Comment by MarcoM65** [comment]
I had to use 

`genisoimage -o rhel8_ks.iso -V "OEMDRV" ks.cfg`

and then place the iso where vsphere could reach it to attach with CDROM.

**Comment by iacuser** [comment]
> I had to use
> 
> `genisoimage -o rhel8_ks.iso -V "OEMDRV" ks.cfg`
> 
> and then place the iso where vsphere could reach it to attach with CDROM.

Can you give a hint how the boot_command in the template should look like to use the generated rhel8_ks.iso?

**Comment by MarcoM65** [comment]
@iacuser 
for boot command I just used the below

```
"variables": {
    "ks_iso": "[datastore] ISOs/rhel8_ks.iso",
```

```
"iso_paths": [
      	"{{user `rhel_iso`}}",
	"{{user `vmtools_iso`}}",
        "{{user `ks_iso`}}"
```
...

   `   "boot_command": "<enter> <enter>"`
  
just to get through the bootup selection for installing.  When it senses the Image it loads iso, reads the "OEMDRV" label and continues from there with kickstarter.   hope that helps.

**Comment by iacuser** [comment]
@MarcoM65 
This was indeed helpful thank you.

I had to adapt the boot command though, to make sure the correct kickstart file is used.

`"boot_command": "<wait10><tab>linux inst.ks=hd:/dev/sr1:ks_rhel8.cfg<enter>"`

**Comment by yakhatape** [comment]
On my side its working for RHEL8 with following boot command : 
` "boot_command": [
        "<up><wait><tab> text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks-rhel8-{{user `vsphere_datacenter`}}-integration.cfg ip={{user `template_ip`}}::{{user `template_gateway`}}:{{user `template_cidr`}}:templaterhel8:ens192:none <enter>"
]`

Hope this will help

**Comment by wixregiga** [comment]
This will probably help a bunch of people here. In order to use this on your local machine with vcenter, all you have to do is:

1. specify the ks file that you want in `cd_files` 
2. download xorriso on your system
3. make the `cd_label = "OEMDRV"`
4. Somewhere in your `boot_command` do the following `linux inst.ks=hd:/dev/sr1:<path_to_ks_file>`
5. OPTIONAL:  `http_content =  null`

Packer will add your kickstart file to the datastore in an iso or whatever you want to make and attach the image to the VM. If a CD has a label of `OEMDRV` then RHEL8 and above will use that images kickstart file to boot the current one. Let me know if this helped.
