### ISSUE TITLE
Datacenter not found when / is in the name

### ISSUE THREAD

**Issue by PshNinja** [jetbrains-infra/packer-builder-vsphere#293]
I'm receiving an error datacenter not found when the "/" character is in the datacenter name. The datacenter is NOT in a folder. Is there a way to escape this character? I'm using vsphere-iso.

**Comment by nslracer** [comment]
Try placing a "\" before the "/" and see if that helps. Providing your configuration would also help us understand what you're trying to do.

**Comment by PshNinja** [comment]
I've tried escaping with ' and " however both produce errors:
Error without escaping:
Build 'vsphere-iso' errored: datacenter 'vSphere Environment - A/B' not found

With "/":
Failed to parse template: Error parsing JSON: invalid character '/' after object key:value pair

WIth '/':
Build 'vsphere-iso' errored: datacenter 'vSphere Environment - A'/'B' not found

My file works fine in another vCenter that doesn't have a / in the datacenter name, but here it is with sensitive info removed:

```
{
  "variables": {
    "VCPassword": "",
    "WinRMPassword": ""
  },
  "sensitive-variables": ["VCPassword", "WinRMPassword"],
    "builders": [
       {
        "type": "vsphere-iso",
        "vcenter_server": "vcapp.my.domain",
        "insecure_connection": "true",
        "datacenter": "vSphere Environment - A/B",
        "username": "packeruser@my.domain",
        "password": "{{user `VCPassword`}}",
        "cluster": "vSphere Tier 2",
        "host": "esxi02p.my.domain",
        "communicator": "winrm",
        "winrm_username": "Administrator",
        "winrm_password": "{{user `WinRMPassword`}}",
        "vm_name":  "Server 2016 DEV",
        "folder": "Templates/Base_Images",
        "convert_to_template": "true",
        "cpus": "4",
        "ram": "8192",
        "RAM_hot_plug": "true",
        "network": "VLAN60",
        "network_card": "vmxnet3",
        "datastore": "Tier 2 Storage Cluster",
        "disk_controller_type": "pvscsi",
	      "guest_os_type": "windows9Server64Guest",
        "disk_thin_provisioned": true,
        "disk_size": "81920",
        "iso_paths": [
          "[NFS_01] ISO/Windows/windows_server_2016_pvscsi.iso",
          "[] /vmimages/tools-isoimages/windows.iso"
        ],
        "floppy_files": [
          "setup/autounattend.xml",
          "setup/setup.ps1",
          "setup/vmtools.cmd"
        ]
       }
    ],
    "provisioners": [
      
    ]
  }
```

**Comment by nslracer** [comment]
Hmmm...I'm having no luck either with a / in the datacenter name. Spaces work fine. Any way you can just rename the datacenter object?

**Comment by PshNinja** [comment]
Seems I'm going to have to go that route. I was trying to avoid it due to the process of getting approvals.

**Comment by neogen19** [comment]
Can you try using %%2f instead of /. I had a similar issue with VLAN and had to replace this character. Not 100% certain but you can try.

**Comment by PshNinja** [comment]
Thank you, @neogen19, %2f (single % was needed) worked perfectly.
