### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by WebSpider** [jetbrains-infra/packer-builder-vsphere#294]
Hi!

The last release from this builder was almost a year ago, and there have been a number of bugfixes and new funtctionality in master that have not yet been released.

How can I help create a new release?

**Comment by bhundven** [comment]
The vsphere-iso builder is now upstream (in the up-coming 1.5.2 release):

https://github.com/hashicorp/packer/blob/master/CHANGELOG.md

I feel that this project should update the project description, and set this project to read-only @mkuzmin @VladRassokhin

**Comment by WebSpider** [comment]
Closing and awaiting the release
