### ISSUE TITLE
Can't get vsphere-clone to read my provisioners. v2.1

### ISSUE THREAD

**Issue by RenMG** [jetbrains-infra/packer-builder-vsphere#297]
code:
```
{
  "variables": {
    "vsphere_server": "",
    "vsphere_user": "",
    "vsphere_password": "",
    "vsphere_host": "",
    "vsphere_datastore": "",
    "vsphere_datacenter":"",
    "vsphere_cluster": "",
    "resource_pool":"",
    "vsphere_template_name": "",
    "clone_vm_name": ""
  },
  "sensitive-variables": ["vsphere_password"],
  "builders": [
    {
        "type": "vsphere-clone",

        "vcenter_server": "{{user `vsphere_server`}}",
        "username": "{{user `vsphere_user`}}",
        "password": "{{user `vsphere_password`}}",
        "insecure_connection": "true",

        "datacenter": "{{user `vsphere_datacenter`}}",
        "cluster": "{{user `vsphere_cluster`}}",
        "resource_pool": "{{user `resource_pool`}}",
        "datastore": "{{user `vsphere_datastore`}}",
        "host":  "{{user `vsphere_host`}}",

        "template": "{{user `vsphere_template_name`}}",
        "vm_name": "{{user `clone_vm_name`}}",

        "communicator": "none"
    }
  ],
  "provisioners":[
    {
      "type": "windows-update",
      "only": ["vsphere-clone"],
      "search_criteria": "AutoSelectOnWebSites=1 and IsInstalled=0",
      "filters": [
        "exclude:$_.Title -like '*Preview*'",
        "include:$true"
      ],
      "update_limit": 25
    },
    {
      "type": "powershell",
      "inline": ["echo hello"]
    }
  ]
}
```

Output:
```
.\Binaries\packer.exe build -force -var-file="ConfigFiles\VMWare\vars_clone_wu_important.json" "ConfigFiles\VMWare\vmware_Win10_1903_clone_update_important.json"
vsphere-clone output will be in this color.

==> vsphere-clone: the vm/template SI-Win10_1903_64-wu-Important already exists, but deleting it due to -force flag
==> vsphere-clone: Cloning VM...
Build 'vsphere-clone' finished.

==> Builds finished. The artifacts of successful builds are:
--> vsphere-clone: SI-Win10_1903_64-wu-Important
```

As you can see there's no output for windows-update which is the provisioner.  If i remove that type and just use the echo command only, still no output.

if i add these provisioners into a vsphere-iso file it works.   

Not sure, but i see that it SHOULD be allowing provisioners...i'm going to redownload packer and see if that may be an issue, but any help would be great.

**Comment by danonh** [comment]
You need to define communitator to winrm or ssh and provide administrator username and password. If communicator is not defined, your cloned VM won't be even powered on after deployment.  Windows-update provisioner is currently in version 0.8, not sure what you are referencing in the title using 2.1? Do you mean jetbrains vsphere builder version? Regards,

**Comment by RenMG** [comment]
I'll add the communicator back in, i believe i initially had that in place and i still had issues.  

I'm using vsphere-clone 2.1.

Thanks for responding i'll play around with this now!

**Comment by RenMG** [comment]
my clone machine is not connecting with WinRM.

Base image build with winrm connected:
` .\Binaries\packer.exe build -on-error=ask -force -var-file="ConfigFiles\VMWare\vars_si_base.json" "ConfigFiles\VMWare\vmware_Win10_1903_si_base.json"
vsphere-iso output will be in this color.

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mount ISO images...
==> vsphere-iso: Creating floppy disk...
    vsphere-iso: Copying files flatly from floppy_files
    vsphere-iso: Copying file: setup/autounattend.xml
    vsphere-iso: Copying file: setup/winrm_ansible.ps1
    vsphere-iso: Copying file: setup/vmtools.cmd
    vsphere-iso: Copying file: setup/user_setup.ps1
    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : []
    vsphere-iso: Done copying paths from floppy_dirs
==> vsphere-iso: Uploading created floppy image
==> vsphere-iso: Adding generated Floppy...
==> vsphere-iso: Adding Floppy image...
==> vsphere-iso: Set boot order temporary...
==> vsphere-iso: Power on VM...
==> vsphere-iso: Waiting for IP...
==> vsphere-iso: IP address: 10.157.224.6
==> vsphere-iso: Using winrm communicator to connect: 10.157.224.6
==> vsphere-iso: Waiting for WinRM to become available...
    vsphere-iso: WinRM connected.
    vsphere-iso: #< CLIXML
    vsphere-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> vsphere-iso: Connected to WinRM!
==> vsphere-iso: Provisioning with Powershell...
==> vsphere-iso: Provisioning with powershell script: C:\Users\rgoodman\AppData\Local\Temp\powershell-provisioner995023147
    vsphere-iso: hello
==> vsphere-iso: Executing shutdown command...
==> vsphere-iso: Deleting Floppy drives...
==> vsphere-iso: Deleting Floppy image...
==> vsphere-iso: Eject CD-ROM drives...
==> vsphere-iso: Clear boot order...
Build 'vsphere-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso: SI-Win10_1903_64_Silver-Packer`


Running my vsphere-clone off the VM artifact:
` .\Binaries\packer.exe build -force -var-file="ConfigFiles\VMWare\vars_clone_wu_important.json" "ConfigFiles\VMWare\vmware_Win10_1903_clone_update_important.json"
vsphere-clone output will be in this color.

==> vsphere-clone: Cloning VM...
==> vsphere-clone: Power on VM...
==> vsphere-clone: Waiting for IP...
==> vsphere-clone: IP address: fdf1:9666:a9d:192:b8bc:4028:c2f:68de
==> vsphere-clone: Using winrm communicator to connect: fdf1:9666:a9d:192:b8bc:4028:c2f:68de
==> vsphere-clone: Waiting for WinRM to become available...
==> vsphere-clone: Timeout waiting for WinRM.
==> vsphere-clone: Power off VM...
==> vsphere-clone: Destroying VM...
Build 'vsphere-clone' errored: Timeout waiting for WinRM.

==> Some builds didn't complete successfully and had errors:
--> vsphere-clone: Timeout waiting for WinRM.

==> Builds finished but no artifacts were created.`

Taking the base image and testing connectivity to winrm:
`renmg@WL-5ZFQST2:~$ curl --insecure -I POST https://10.157.224.12:5986/wsman -vvv
* Rebuilt URL to: POST/
* Could not resolve host: POST
* Closing connection 0
curl: (6) Could not resolve host: POST
*   Trying 10.157.224.12...
* TCP_NODELAY set
* Connected to 10.157.224.12 (10.157.224.12) port 5986 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=******
*  start date: Dec 19 05:05:49 2019 GMT
*  expire date: Dec 16 05:05:49 2029 GMT
*  issuer: CN=******
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fffe60d8580)
> HEAD /wsman HTTP/2
> Host: 10.157.224.12:5986
> User-Agent: curl/7.58.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 405
HTTP/2 405
< allow: POST
allow: POST
< server: Microsoft-HTTPAPI/2.0
server: Microsoft-HTTPAPI/2.0
< date: Fri, 20 Dec 2019 13:17:58 GMT
date: Fri, 20 Dec 2019 13:17:58 GMT

<
* Connection #1 to host 10.157.224.12 left intact`

I tried adding in my autounattend a prioritize ipv4, but that added a lot of other drama.  I'm still going to try to make this fit.

thanks for the help!

**Comment by danonh** [comment]
Not sure why you use v2.1 as 2.3 is available for more than over a year. I use beta build from this site and it works as expected: https://teamcity.jetbrains.com/viewLog.html?buildId=2529292&buildTypeId=PackerVSphere_Build&tab=artifacts
Hope your windows-update provisioner has been downloaded and placed in same directory as your packer executable? https://github.com/rgl/packer-provisioner-windows-update/releases

**Comment by RenMG** [comment]
ok i'll double check and download the recent.  I've been debugging this so i'm definitely at a point where i'm not sure what was a win vs a failure.

**Comment by danonh** [comment]
This is probably your problem. If you have disabled winrm on your base image, your clone won't be able to communicate over winrm and perform customization (windows update). What I usually do is create base image with unsecured winrm enabled, then on my clones I change WinRM to pristine state. Base image is not used for production, only clones which have proper WinRM state

**Comment by RenMG** [comment]
WinRM is communicating on the base image on with the ansible winrm script.  what i don't understand is why on the clone that same base image attempts to communicate on ipv6, which i would assume shouldn't make a difference, but you gave me an idea.  Let me take this back the the drawing board.

Thanks

**Comment by danonh** [comment]
I disable IPv6 during the installation. IPv6 cmd is part of my autounattend.xml file so each time packer completes building process IPv6 is off.

**Comment by RenMG** [comment]
Do you re-enable it after all is said and done?

**Comment by danonh** [comment]
No, I don't re-enable it,  I don't need to have IPv6  enabled on my golden image.

**Comment by RenMG** [comment]
Thanks so much for your time! you helped a lot! i got it to work by disabling ipv6.  I'll have to bring it up to my stake holders, but as of now that was the solution.  again, i really appreciate your time.
