### ISSUE TITLE
Build 'vsphere' errored: NotAuthenticated

### ISSUE THREAD

**Issue by Kutkovsky** [jetbrains-infra/packer-builder-vsphere#30]
Hello, guys!
We are using your plugin to clone VM's and provision them at vSphere 6.5.
Faced up with situation when our job fails with error:

```
==> vsphere: Executing shutdown command...
packer-builder-vsphere: 2017/08/09 08:04:47 Shutdown command: sudo shutdown -h now
packer-builder-vsphere: 2017/08/09 08:04:47 opening new ssh session
packer-builder-vsphere: 2017/08/09 08:04:47 starting remote command: sudo shutdown -h now
packer-builder-vsphere: 2017/08/09 08:04:47 Waiting max 5m0s for shutdown to complete
==> vsphere: Power off VM...
==> vsphere: NotAuthenticated
==> vsphere: Destroying VM...
==> vsphere: ServerFaultCode: The session is not authenticated.
[INFO] (telemetry) ending vsphere
[INFO] (telemetry) found error: NotAuthenticated
Build 'vsphere' errored: NotAuthenticated
```

VM clearly shutdown and stays at vSphere (its fine, but our job fails with error). So plugin cannot destroy VM due to not authenticated session also.

Our job takes 3.5 hours usually. So, when we shortened our task to 25 min just for test - it succeed. With any long-duration tries - failed.

I found an article at vmware.com saying that we can increase timeout constraints at vSphere to resolve this:
[https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2040626](url)
It didn't help us. So I want to ask you, could you add some kind of Keep Alive packets during the job? Or reestablish session to vSphere at the end of the job?

Sure, this will fix this issue.

**Comment by mkuzmin** [comment]
This is tricky. I've reproduced it locally, but cannot find a fix yet.

**Comment by mkuzmin** [comment]
I suppose I've solved that. But please test the fix, before I merge it into master.
https://github.com/jetbrains-infra/packer-builder-vsphere/releases/tag/v.1.3.1.dev1

**Comment by Kutkovsky** [comment]
@mkuzmin Sure, will test it today. Thanks

**Comment by Kutkovsky** [comment]
@mkuzmin Thanks! Confirm! The bug gone. No more such errors.
