### ISSUE TITLE
fork/exec /opt/packer_1.5.1: permission denied

### ISSUE THREAD

**Issue by Runkar** [jetbrains-infra/packer-builder-vsphere#300]
Hey,

i ran into this error with the newest version of packer (v1.5.1): 
````
Failed to initialize build 'vsphere-iso': error initializing builder 'vsphere-iso': fork/exec /opt/packer_1.5.1: permission denied

==> Builds finished but no artifacts were created.
````

I checked all file- and user-permissions on both the host and the vCenter. With the previous v1.4.5 of packer everything works fine. Can you confirm this?

RHEL 7.7
Packer v1.5.1
vsphere-builder 2.3

**Comment by cattywampus** [comment]
I'm seeing the same error on my Mac (Catalina 10.15.2). Using Packer 1.5.1 (installed via home-brew) with `vsphere-iso` gives me that error:

```
Failed to initialize build 'vsphere-iso': error initializing builder 'vsphere-iso': fork/exec /usr/local/bin: permission denied

==> Builds finished but no artifacts were created.
```

Rolling back to `1.4.5` worked for me. Thanks for the workaround tip.

**Comment by amikkelsendk** [comment]
I see the same error on v.1.5.1 on CentOS. 

On 14.01.2020 13:17, Jens Schütz wrote:

> Hey, 
> 
> i ran into this error with the newest version of packer (v1.5.1):
> 
> Failed to initialize build 'vsphere-iso': error initializing builder 'vsphere-iso': fork/exec /opt/packer_1.5.1: permission denied
> 
> ==> Builds finished but no artifacts were created.
> 
> I checked all file- and user-permissions on both the host and the vCenter. With the previous v1.4.5 of packer everything works fine. Can you confirm this? 
> 
> RHEL 7.7
> Packer v1.5.1
> vsphere-builder 2.3 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/jetbrains-infra/packer-builder-vsphere/issues/300?email_source=notifications&amp;email_token=AILSAWTZIMHBEWWQMILMYFDQ5WUMXA5CNFSM4KGSBMX2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGBE7NQ
[2]

**Comment by smithhannahm** [comment]
Looks like there were some backwards incompatibilities introduced in [packer v1.5.0](https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#150-december-18-2019), specifically:

> core: Changes have been made to both the Prepare() method signature on the builder interface and on the Provision() method signature on the provisioner interface. [GH-7866]

**Comment by iDustbin** [comment]
hi, im running into he same issue.
looks like the packer binary would try to execute something in your ~ (userhome) 
my system

debian 10.2
packer 1.5.1
vsphere builder 2.3

ugly hotfix 
use an older packer version. 
actually downgraded to packer 1.4.5. 
or fix the permission issue...

**Comment by bhundven** [comment]
https://github.com/jetbrains-infra/packer-builder-vsphere/issues/294

vsphere-iso is in the upcoming 1.5.2 packer release, you should download the pre-release and test.

**Comment by bhundven** [comment]
Sorry, I meant the nightly release: 

https://github.com/hashicorp/packer/releases

**Comment by Runkar** [comment]
> #294
> 
> vsphere-iso is in the upcoming 1.5.2 packer release, you should download the pre-release and test.

That is great news!! Didn't expect that to happen after my previous conversation with Hashicorp.
So I guess with the release of packer v1.5.2 this issue is outdated. I will close it after the official release.

**Comment by ccoager** [comment]
vsphere-clone is also broke but I don't see any mention of that in the 1.5.2 release.  Any idea when this will be addressed?

**Comment by smithhannahm** [comment]
@ccoager Both vsphere-clone and vsphere-iso are in the new 1.5.2 release, though the changelog doesn't make that particularly clear. I've tested some of our vsphere-clone templates with the nightly build, and they worked without modification.

**Comment by zyra83** [comment]
Same thing here with packer 1.5.1.

**Comment by bhundven** [comment]
@zyra83 see: https://github.com/jetbrains-infra/packer-builder-vsphere/issues/300#issuecomment-577390975

**Comment by Runkar** [comment]
After the official hashicorp release this issue is outdated.
Thank you!
