### ISSUE TITLE
Is there output option

### ISSUE THREAD

**Issue by brlbil** [jetbrains-infra/packer-builder-vsphere#304]
I could not find any mention of an output option in which the created image would be exported as ova or ovf artifact.

Is there such a capability? If yes, how can I configure it? If not, are there any plans to implement it?

**Comment by jhawk28** [comment]
just a heads up, packer proper merged in the vsphere plugins: https://github.com/hashicorp/packer/pull/8480

**Comment by bhundven** [comment]
https://github.com/jetbrains-infra/packer-builder-vsphere/issues/294

https://github.com/hashicorp/packer/blob/master/CHANGELOG.md

**Comment by brlbil** [comment]
Thanks for the heads up, I will follow packer.
