### ISSUE TITLE
Add support Secure Boot to VM

### ISSUE THREAD

**Issue by boss-chifra** [jetbrains-infra/packer-builder-vsphere#305]
I set "firmware": "efi" but I need also "Secure Boot" flag
![image](https://user-images.githubusercontent.com/1705857/74225277-ad19d200-4cba-11ea-8143-bd0b19961101.png)

**Comment by VladRassokhin** [comment]
Related issue in packer repo — https://github.com/hashicorp/packer/issues/8873.
Since this repo is obsolete I'm closing this issue, please subscribe to one above.
