### ISSUE TITLE
Support latest version of Packer 1.5.x

### ISSUE THREAD

**Issue by jmgilman** [jetbrains-infra/packer-builder-vsphere#306]
The latest version of Packer at the time of this writing is 1.5.4. When attempting to use either the vsphere-iso or vsphere-clone plugins with this version, it generates an API error. 

packer-builder-vsphere v2.3 only supports API **version 4**
packer 1.5.4 uses API **version 5**

Currently, I'm having to revert to using Packer 1.4.5 to get the plugins to work.

**Comment by holdenSK** [comment]
AFAIK, vsphere-iso is now integrated into core packer build.

**Comment by codefox42** [comment]
Yes - [since 1.5.2](https://github.com/hashicorp/packer/blob/v1.5.4/CHANGELOG.md#152-february-12-2020). :-) I needed to uninstall the old plugin (i.e. remove it from any of the plugin paths) before packer used the bundled provisioner.

Though, a hint in the main readme would be helpful.

**Comment by jmgilman** [comment]
Ah, that's not surprising considering how useful these plugins were. Thanks!

**Comment by mooperd** [comment]
Hi - so the vsphere-iso is being merged but the vsphere-clone is being dropped?

**Comment by codefox42** [comment]
Both builders have been merged - see also the official docs: [vsphere-iso](https://packer.io/docs/builders/vsphere-iso.html), [vsphere-clone](https://packer.io/docs/builders/vsphere-clone.html)

**Comment by mooperd** [comment]
Thats wonderful! thanks!

One thing which is confusing me about "vsphere-clone" is how I can use the official ubuntu images which have no password. Can "vsphere-clone" inject its own credentials into the image the same as AWS/Google or does the base image have to have a known username/password preseeded?

**Comment by mooperd** [comment]
I don't think "vsphere-clone" was added to packer - there is only mention of vsphere-iso in the packer changelog. `"type": "vsphere-clone"` produces an error `Failed to initialize build 'vsphere-clone': error initializing builder 'vsphere-clone': fork/exec /usr/local/bin/packer-builder-vsphere-clone: no such file or directory`

**Comment by jmgilman** [comment]
This is outside the scope of this issue, but I'll comment on your question:

If you're trying to build from an ISO, you're likely already using a preseed to automate the installation. You'll have to hardcode a password into the preseed if you want to be able to immediately provision the OS when it comes up. 

In our case our provisioner immediately changes the password once it connects using the password created in the preseed (we also only do key based SSH authentication anyways, so it's a moot point for security). You could alternatively dynamically fill in the preseed password at runtime before handing it off to Packer. 

I'm going to close this issue since the original ask has technically been achieved through adoption from Packer.
