### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by mooperd** [jetbrains-infra/packer-builder-vsphere#308]
Hi,

I noticed that this package is not working with the latest versions of packer and hasn't had a release in a really long time. Should I find another toolchain for this kinda stuff? 

Cheers,

Andrew

**Comment by thorsteinbn** [comment]
Hi
This project has been merged in to the official packer plugins. 

https://github.com/hashicorp/packer/pull/8480

**Comment by codefox42** [comment]
@mooperd, see also #306 - this plugin has been merged into the official packer source tree. Unfortunately a small hint regarding this great change is missing in the readme of this repository.

**Comment by VladRassokhin** [comment]
I've added deprecation notice
