### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by paasi6666** [jetbrains-infra/packer-builder-vsphere#310]
It's only a minor issue but:
The [link ](https://pubs.vmware.com/vsphere-6-5/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.vm.GuestOsDescriptor.GuestOsIdentifier.html)on guest_os_type in the README.md file doesn't work any more.

**Comment by VladRassokhin** [comment]
This repo is deprecated. Seems it was fixed in [official Packer repository](https://github.com/hashicorp/packer).
