### ISSUE TITLE
winrm connection via IPv6 fails "link-local"

### ISSUE THREAD

**Issue by MarcoM65** [jetbrains-infra/packer-builder-vsphere#316]
when running packer on Red Hat system with 2 NICs I get the below error:
  
```
==> vsphere-iso: Power on VM...
2020/06/01 07:12:27 packer-builder-vsphere-iso plugin: [INFO] Waiting for IP, up to total timeout: 1h30m0s, settle timeout: 10m0s
==> vsphere-iso: Waiting for IP...
2020/06/01 07:19:36 packer-builder-vsphere-iso plugin: VM IP aquired: fe80::4018:a84e:a508:f5aa
2020/06/01 07:19:36 packer-builder-vsphere-iso plugin: VM IP is still the same: fe80::4018:a84e:a508:f5aa
....
2020/06/01 07:29:37 packer-builder-vsphere-iso plugin: VM IP is still the same: fe80::4018:a84e:a508:f5aa
2020/06/01 07:29:37 packer-builder-vsphere-iso plugin: VM IP seems stable enough: fe80::4018:a84e:a508:f5aa
==> vsphere-iso: IP address: fe80::4018:a84e:a508:f5aa
==> vsphere-iso: Using winrm communicator to connect: fe80::4018:a84e:a508:f5aa
2020/06/01 07:29:37 packer-builder-vsphere-iso plugin: Waiting for WinRM, up to timeout: 30m0s
==> vsphere-iso: Waiting for WinRM to become available...
2020/06/01 07:29:37 packer-builder-vsphere-iso plugin: [INFO] Attempting WinRM connection...
2020/06/01 07:29:37 packer-builder-vsphere-iso plugin: [DEBUG] connecting to remote shell using WinRM
2020/06/01 07:29:37 packer-builder-vsphere-iso plugin: [ERROR] connection error: unknown error Post https://fe80::4018:a84e:a508:f5aa:5986/wsman: dial tcp [fe80::4018:a84e:a508:f5aa]:5986: connect: invalid argument

....
2020/06/01 07:59:32 packer-builder-vsphere-iso plugin: [DEBUG] connecting to remote shell using WinRM
2020/06/01 07:59:32 packer-builder-vsphere-iso plugin: [ERROR] connection error: unknown error Post https://fe80::4018:a84e:a508:f5aa:5986/wsman: dial tcp [fe80::4018:a84e:a508:f5aa]:5986: connect: invalid argument
2020/06/01 07:59:32 packer-builder-vsphere-iso plugin: [ERROR] WinRM connection err: unknown error Post https://fe80::4018:a84e:a508:f5aa:5986/wsman: dial tcp [fe80::4018:a84e:a508:f5aa]:5986: connect: invalid argument
==> vsphere-iso: Timeout waiting for WinRM.
==> vsphere-iso: Clear boot order...
2020/06/01 07:59:37 packer-builder-vsphere-iso plugin: [INFO] WinRM wait cancelled. Exiting loop.
==> vsphere-iso: Power off VM...
==> vsphere-iso: Deleting Floppy image ...
2020/06/01 07:59:38 packer-builder-vsphere-iso plugin: Deleting floppy disk: /tmp/packer071504647
==> vsphere-iso: Destroying VM...
```

When using wireshark I see no IPv6 traffic leaving packer system interfaces.  I am able to connect to window VM winrm port using 
`openssl s_client -connect fe80::4018:a84e:a508:f5aa%4]:5986` 
just not sure why packer doesn't process ipv6 link-local address correctly.  Is this a limitation?
I even verified local firewall wasn't preventing network traffic out.
Also disable ipv6 off of 1st NIC to prevent that being used.

**Comment by MarcoM65** [comment]
tried with a linux vm with IPv6 using link-local to connect via ssh and got the following error.

> 2020/06/01 11:24:08 packer-builder-vsphere-iso plugin: [INFO] Waiting for SSH, up to timeout: 5m0s
> 2020/06/01 11:24:08 packer-builder-vsphere-iso plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp: address fe80::250:56ff:fe83:70d1:22: too many colons in address
> ==> vsphere-iso: Waiting for SSH to become available...
> 2020/06/01 11:24:13 packer-builder-vsphere-iso plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp: address fe80::250:56ff:fe83:70d1:22: too many colons in address
> 2020/06/01 11:24:18 packer-builder-vsphere-iso plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp: address fe80::250:56ff:fe83:70d1:22: too many colons in address

so it might be packer method of parsing IPv6 syntax for communicating. 

I'm able to connect via openssl in the following way.

> openssl s_client -connect  [fe80::250:56ff:fe83:70d1%ens224]:22

**Comment by VladRassokhin** [comment]
I suppose it duplicates https://github.com/hashicorp/packer/issues/9349

**Comment by MarcoM65** [comment]
@VladRassokhin 
no it wasn't the same issue.  This one is specific that I do want to use IPv6.  But might be in wrong community post.

Added my comments to hashicorp/packer community board: hashicorp/packer-plugin-vsphere#182
