### ISSUE TITLE
Are resource pools mandatory to have on the vsphere server?

### ISSUE THREAD

**Issue by SurferL** [jetbrains-infra/packer-builder-vsphere#41]
While not setting a `resource_pool` in the builder settings, and not have a resource pool on the vsphere host, I have the following error:
```
Build 'vsphere' errored: resource pool '/Data Center/host/Production/esxi-server/Resources/' not found
```
Any ideas?

**Comment by SurferL** [comment]
Got confused with the hierarchy of vsphere. Goes:
```
Hosts & Clusters
|---> Data Center
          |---> Root Resource pool (aka Cluster)
          |---> Host
          |---> VMs
```
So the root resource pool for me was in fact `Production`.

**Comment by mkuzmin** [comment]
We still not fully support clusters. It will be added as part of #38.
