### ISSUE TITLE
winrm_username and password

### ISSUE THREAD

**Issue by MJA1** [jetbrains-infra/packer-builder-vsphere#44]
Hello,

I am trying to create a windows image using the vsphere plugin, but I wasn't able to do that since ssh is mandatory. Is there any workaround or plan to add windows support?
 "winrm_username": "Administrator",
"winrm_password": "{{user `guest_password`}}",

Kind Regards,
Makram.

**Comment by mkuzmin** [comment]
This is a common Packer issue. Provisioning Windows you have to enable WinRM explicitly: `"communicator": "winrm"`

**Comment by MJA1** [comment]
Thank you @mkuzmin
