### ISSUE TITLE
Support for Windows Templates?

### ISSUE THREAD

**Issue by exbane** [jetbrains-infra/packer-builder-vsphere#48]
Good afternoon,

Will this work with Windows Templates within vSphere? i noticed that the ssh_username is mandatory - which leads me to believe that we cannot use a Windows template as the source. From a VMware perspective though it shouldn't need the u/p to do the cloning procedure. Obviously the provisioner will need access to run any scripts (powershell) after the fact. 

Thank you, 

Adam

**Comment by exbane** [comment]
Nevermind - I went through the closed issues and found what i was looking for.. You can close this.

**Comment by mkuzmin** [comment]
Yes, Windows guests are supported by   `"communicator": "winrm"`, `winrm_username`, and `winrm_password` options.

**Comment by jcoconnor** [comment]
@mkuzmin is there a plan to document this in the Front End Readme for the project ?
