### ISSUE TITLE
Failed to initialize build 'vsphere'

### ISSUE THREAD

**Issue by DarrenRatcliffe** [jetbrains-infra/packer-builder-vsphere#58]
I am trying to use the vsphere plugin within a Jenkins job along with the Packer Jenkins plugin. I download the plugin and chmod the plugin as described (as a build - execute shell - command). However Packer throws an error when running:

Failed to initialize build 'vsphere': error initializing builder 'vsphere': fork/exec /var/lib/jenkins/jobs/accosia2/workspace/packer-builder-vsphere.linux: exec format error

Jenkins 2.89.4
Packer 1.1.2
vsphere-builder 1.6

**Comment by mkuzmin** [comment]
Are you calling `packet-builder-vsphere` binary directly?
This is a plugin. It should be used together with main `packer` binary.

**Comment by DarrenRatcliffe** [comment]
@mkuzmin no packer is calling it and the error above is what packer throws when it tries to load it. I am placing it in the current directory and have tried placing it the same directory as the packer binary. same result both times.

**Comment by DarrenRatcliffe** [comment]
@mkuzmin this is what I am using to download the plugin:
`curl "https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v1.6/packer-builder-vsphere.linux" > "packer-builder-vsphere.linux"
chmod +x packer-builder-vsphere.linux`

**Comment by DarrenRatcliffe** [comment]
@mkuzmin a bit more info:
`+ pwd

/var/lib/jenkins/jobs/accosia3/workspace

+ curl https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v1.5/packer-builder-vsphere.linux

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed


  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   618    0   618    0     0    535      0 --:--:--  0:00:01 --:--:--   535

+ chmod +x /var/lib/jenkins/jobs/accosia3/workspace/packer-builder-vsphere.linux

+ ls -l

total 52

-rw-r--r-- 1 default root  499 Mar 13 10:08 notes.txt

-rw-r--r-- 1 default root 1187 Mar 13 10:08 packer2.json

-rw-r--r-- 1 default root 2220 Mar 13 10:08 packer3.json

-rw-r--r-- 1 default root  158 Mar 13 10:08 packer4.json

-rwxr-xr-x 1 default root  618 Mar 13 10:17 packer-builder-vsphere.linux

-rw-r--r-- 1 default root  730 Mar 13 10:08 packer.json

-rw-r--r-- 1 default root  101 Mar 13 10:08 playbook.yml

-rw-r--r-- 1 default root  430 Mar 13 10:08 README.md

-rw-r--r-- 1 default root 1692 Mar 13 10:08 RHEL-6-8.1.json

-rw-r--r-- 1 default root 1528 Mar 13 10:08 RHEL-6-8.json

drwxr-xr-x 2 default root 4096 Mar 13 10:08 scripts

-rw-r--r-- 1 default root  271 Mar 13 10:08 test.json

-rw-r--r-- 1 default root 1283 Mar 13 10:08 vsphere.json

[workspace] $ /var/lib/jenkins/tools/biz.neustar.jenkins.plugins.packer.PackerInstallation/packer/packer build /var/lib/jenkins/jobs/accosia3/workspace/vsphere.json

Failed to initialize build 'vsphere': error initializing builder 'vsphere': fork/exec /var/lib/jenkins/jobs/accosia3/workspace/packer-builder-vsphere.linux: exec format error
`

**Comment by DarrenRatcliffe** [comment]
Actually I have just tried is (packer-builder-vsphere v1.6 & packer v1.1.2) on a fresh install of CentOS 7 (no Jenkins) and I get the same error, so it doesn't look like it is an issue with Jenkins

**Comment by DarrenRatcliffe** [comment]
Sorry its me I am stupid, I used curl not wget, it works now
