### ISSUE TITLE
Plugin fails to find host when cluster name isn't `hosts`

### ISSUE THREAD

**Issue by Nyoroon** [jetbrains-infra/packer-builder-vsphere#64]
Plugin fails to find host when cluster name is not `hosts`:
```fmt.Sprintf("/%v/host/%v", d.datacenter.Name(), name)```

**Comment by Nyoroon** [comment]
Didn't notice #38

**Comment by ideologysec** [comment]
@Nyoroon clusters are/should be, supported as of 2.0 beta 4.
