### ISSUE TITLE
Support for NestedHV for iso builder

### ISSUE THREAD

**Issue by casey-robertson** [jetbrains-infra/packer-builder-vsphere#67]
Would like support for the NestedHV VM build option (for running 1709 Windows on vSphere to support the Hyper-V role).

**Comment by casey-robertson** [comment]
I would do this but can't get the plugin to build on my machine :-(

**Comment by mkuzmin** [comment]
Feel free to ask any questions right in this issue

**Comment by casey-robertson** [comment]
Thanks - I'm off to SRECon next week but would love to up my dev game and get some Go experience on this.

**Comment by ScriptXaaS** [comment]
I tried to the following to enable nestVM.  However, it didn't set the needed hardware virtualization on the guest VM:
"configuration_parameters": {
   "featMask.vm.hv.capable": "Min:1",   
   "vhv.enable": "TRUE"
}

**Comment by seanmalloy** [comment]
I started working on a fix for this. I should be submitting a pull request for this in the next few days.
