### ISSUE TITLE
Convert VMs to templates

### ISSUE THREAD

**Issue by mkuzmin** [jetbrains-infra/packer-builder-vsphere#7]
After a VM is created and provisioned, we need a last step: prepare it for long-term usage: as a source in other Packer builds, in Terraform plans, as TeamCity cloud agents.

we need two additional options (independent, disabled by default):
1) to allow linked cloning, a new snapshot should be added
2) base images are usually converted from VMs to templates

**Comment by LizaTretyakova** [comment]
Added in #18. To use this functionality add a line `"to_template": true` to your template file.

**Comment by mkuzmin** [comment]
I've published [release 1.1](https://github.com/jetbrains-infra/packer-builder-vsphere/releases/tag/v1.1).
- `to_template` has been renamed to `convert_to_template`
- added `create_snapshot`
