### ISSUE TITLE
Resource pools not found

### ISSUE THREAD

**Issue by chris-david-taylor** [jetbrains-infra/packer-builder-vsphere#75]
Hi,

When trying to build a template from ISO (vSphere 6.0), the Resource Pool specified in the JSON file is not found by packer;

Build 'vsphere-iso' errored: error creating vm: resource pool '[hostname-redacted]
/Resources/[resource-pool-redacted]' not found

Packer is authenticating against vSphere, and the Datacenter name is set correctly.  Is there an option to set the Cluster name?  I think this worked on MacOS a day or two ago.

packer version: 1.2.1
plugins: 2.0-beta4
OS:  Centos 7.

Let me know if you need further info/debug.

**Comment by mkuzmin** [comment]
`cluster` parameter was added in #61. 
Sorry I still don't have docs updated.

**Comment by chris-david-taylor** [comment]
Ah, I see. I’ll try it on Monday. If it’s OK, I’ll close the issue. Thanks for such a great tool.

**Comment by iejitagha** [comment]
Hi,
Similar to Chris above, I am running on ESX 6.0 and trying to build a template for Centos 7 but still getting the resource pool issue.

My setup/config are as follows:

{
  "builders": [
    {
      "type": "vsphere-iso",

      "vcenter_server": "my_vsphere.com",
      "username": "domainname\\myaccount",
      "password": "xxx",
      "ssh_username": "root",
      "ssh_password": "root",
      "insecure_connection": "true",
      "vm_name": "MYNEWSERVER",
      "cluster": "MY_Cluster",
      "resource_pool": "",
      "datastore": "MY_Datastore",
      "datacenter": "mydc",
      "network": "myNetwork",

      "guest_os_type": "rhel7_64Guest",
      "CPUs": 1,
      "RAM": 4096,
      "disk_controller_type": "pvscsi",
      "disk_size": 2048,
      "disk_thin_provisioned": true,
      "network_card": "vmxnet3",
      "iso_paths": [
        "ISO/myiso.iso"
      ],
      "boot_order": "disk,cdrom",
      "convert_to_template": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": ["date"]
    }
  ]
}
packer version: 1.2.1
 plugins: 2.0-beta4

Failing with:
Build 'vsphere-iso' errored: error creating vm: resource pool 'MY_Cluster/Resources' not found

**Comment by chris-david-taylor** [comment]
Hi @iejitagha ,
I think your issue is that your "resource_pool" parameter is blank.  If you specify the resource pool, and ommit the vSpere host parameter it will work.

Hi @mkuzmin ,  happy to confirm it works now.  I'll close the Issue.

Thanks,
Chris.

**Comment by stacycarter** [comment]
I had this issue as well, but it seems that for me it was permissions related (in my case, I did not specify a resource pool in the json because I'm not using a pool and packer just used the default resource pool name when it ran).  I had delegated permissions for the service account at lower levels in vCenter (ie on the folder, datastore, network).  Found that if I added read-only for the service account to the top [root] of vCenter, the issue went away.

**Comment by olsson-s** [comment]
For me, I just needed to add the fully qualified domain name.  Instead of dev02 (host) and vcenter I switched to dev02.mydomain.com and vcenter.mydomain.com and that fixed the issue.  Note that I can ping dev02 or vcenter directly without any issue, but packer wants the FQDN.

```
Build 'vsphere-iso' errored: error creating vm: resource pool '[hostname-redacted]
/Resources/[resource-pool-redacted]' not found 
```
