### ISSUE TITLE
Specify 'disk_size' in megabytes instead of gigabytes

### ISSUE THREAD

**Issue by mkuzmin** [jetbrains-infra/packer-builder-vsphere#77]
to align with `RAM` parameter

**Comment by sudomateo** [comment]
+1 This aligns the `disk_size` parameter with the `vmare-iso` and `virtualbox-iso` builders.

**Comment by rgl** [comment]
What is stopping this from being implemented? I can supply patch if needed :-)

**Comment by rgl** [comment]
there you go https://github.com/jetbrains-infra/packer-builder-vsphere/pull/95 :-)

**Comment by mkuzmin** [comment]
Fixed by #95
