### ISSUE TITLE
Remove 'boot_order' parameter

### ISSUE THREAD

**Issue by mkuzmin** [jetbrains-infra/packer-builder-vsphere#78]
- Hardcode `disk,cdrom`
- Move from common to ISO-builder only

**Comment by chris-david-taylor** [comment]
Hi @mkuzmin,

I can't help thinking might cause a problem for some scenarios?  I have some (unusual) edge cases this would break. 

Maybe have "disk,cdrom" as default behavior unless boot_parameter is actually in the packer file?

**Comment by mkuzmin** [comment]
If you have any examples - I'm very interested to hear

**Comment by chris-david-taylor** [comment]
Hi @mkuzmin,

Thanks for replying - btw, hope I'm not spamming the project.  Like I said, they are real edge cases, but it is a possibility that others may have them too.  

It's a truly horrible circumstance which requires a reboot and then a second boot from CD - we use a heavily customised Anaconda to launch a session when detecting the disk has an MBR installed, and another environment gets loaded, running scripts which extensively modifies the filesystem.  Alas I do the obvious; write the Boot Loader at a later stage, as it would introduce a breaking change to the installer customisations.  

It's such an edge case that, I'm happy to just clone and build from when fix #82 was committed to master as the existing code base already fulfils my needs perfectly. 

Thanks,

**Comment by mkuzmin** [comment]
This makes a perfect sense. Thanks for the detailded feedback.
I'll leave the parameter in both builders, but add a default value`disk,cdrom` in `vsphere-iso` builder: e59c1326f96aa49976a63a70f1252c59ab093cf0
