### ISSUE TITLE
Build launch an error when a VM/template with the exact same name exists, even using -force

### ISSUE THREAD

**Issue by obokaman-com** [jetbrains-infra/packer-builder-vsphere#88]
First of all, thousand 👏 for your work. It saves us a lot of time on rebuilding the base templates on our infrastructure, ready to be used by Terraform to start the new VMs. 🙇 

We're using our Packer templates to "rebuild" out base Vsphere VMware templates every time our Ansible roles change, so these base templates can be used to start new VMs with the most up-to-date state. The problem is that currenty we are forced to remove the previous builds by hand. When we launch our `packer build` we receive some errors like this:

`Build 'memcached' errored: The name 'MemcachedProvisioned' already exists.`

Would it be possible that when using `-force` param, the remote artifacts could be overwritten by the ones built by current Packer execution?

**Comment by michaelhajjar** [comment]
This would be great, currently using a python script for removing template before using packer

**Comment by mkuzmin** [comment]
We have this feature request in #50
