### ISSUE TITLE
Example of Windows 10 template for 'vsphere-iso' builder

### ISSUE THREAD

**Issue by stacycarter** [jetbrains-infra/packer-builder-vsphere#89]
Testing with the v2.0-beta4 vSphere-ISO Builder.  Deploying Windows Server 2016 using an autounattend.xml.  Was looking at the Windows 10 vSphere-ISO example here: [https://github.com/jetbrains-infra/packer-builder-vsphere/tree/master/examples/windows]. Trying to add the step where vSphere tools gets updated using a specific ISO.  But if I specify two different ISOs in the json in the "iso_paths" section like the example (the ISO I'm using to install Windows, and the ISO for VMware tools), then Windows no longer installs successfully.  Almost like it's trying to install from the wrong ISO.  Maybe I'm missing something here.  If you supply multiple ISOs, how do you control which ISO it uses to try and install Windows?

**Comment by stacycarter** [comment]
Figured it out.  Was accidentally supplying the VMware Tools windows.iso file in the floppy_files section (in addition to the iso_paths section.  Removed it from the floppy_files section and this resolved the issue.

**Comment by venugeddam** [comment]
Hi Stacycarter,

Could you upload your working test json file?

Thanks.
