### ISSUE TITLE
Can't find floppy drive in RancherOS

### ISSUE THREAD

**Issue by codeslingerMalthius** [jetbrains-infra/packer-builder-vsphere#93]
I have a Packer template that uses this builder. I supply the following information:

```
"builders": [
    {
      "type": "vsphere-iso",
      "vcenter_server": "{{user `vcenter_server`}}",
      "host": 			"{{user `esx_host`}}",
      "datacenter": "{{user `vcenter_datacenter`}}",
      "datastore": 	"{{user `vcenter_datastore`}}",
      "username": 	"{{user `vcenter_username`}}",
      "password": 	"{{user `vcenter_password`}}",

      "vm_name": 	"test-vm",
      "disk_size": 	"{{user `vm_disk_size`}}",
      
      "CPUs": 		"{{user `vm_cpu`}}",
      "RAM": 		"{{user `vm_ram`}}",
      
      "network": "VMNetwork 1",
      
      "ssh_username": "{{user `ssh_username`}}",
      "ssh_private_key_file": "{{user `ssh_password_path`}}",
      "ssh_port": 22,
      
      "iso_paths": ["{{user `iso_url`}}"],
      "floppy_files": ["files/cloud-config.yml"],

      "disk_thin_provisioned": true,
      "insecure_connection": true,

      "boot_wait": "60s",
      "boot_order": "disk,cdrom",
      
       "boot_command":[
          "<esc><esc><enter><wait>",
          "sudo ros config set mounts '[[\"/dev/fd0\",\"/media\", \"ext4\",\"\"]]'<wait5>",
          "sudo ros install -d /dev/sda -f -c /media/cloud-config.yml --no-reboot",
          "<enter>"]

    }
  ],
```
The problem is that the Rancher OS operating system doesn't show any floppy drives mounted. /dev contains no fdX for any X.
vSphere shows that there is a floppy drive mapped to a file in the datastore, but it is attached to an "Unknown Device".

**Comment by codeslingerMalthius** [comment]
this is with the Rancher OS downloaded yesterday with [this url](https://github.com/rancher/os/releases/latest)

**Comment by rgl** [comment]
It might be that rancher does not have support for floppy drives. the debian netinst images does not have them. so you might want to try using that iso in VirtualBox first, just to make sure.

**Comment by mkuzmin** [comment]
I have the same issue automating macOS.
As the OS doesn't have drivers for a floppy drive, all the files are placed onto additional CD-ROM.
At the moment I create such ISOs outside of Packer build ([iso-setup.sh](https://github.com/jetbrains-infra/packer-builder-vsphere/blob/master/examples/macos/setup/iso-setup.sh)), and upload them into datastore manually.

Probably we need a feature for dynamic ISO file creation and upload.

**Comment by mkuzmin** [comment]
we now have `http_directory` so preseed file can be provided remotely: #116.
also watch #177 for macOS case.
